Implement more continuous log CDF functions
pymc-devs/pymc pull request #2048
Opened 2017-04-18 11:10 UTC by domenzain

Implement several log CDF functions

The distributions concerned are:
- [x] Pareto
- [x] Flat
- [x] Wald
- [ ] Beta
- [ ] Exponential

Each implementation is then tested against SciPy's own implementation.

2017-04-18 12:02 UTC, domenzain commented
This is done in the context of  #1867 and #1864.
When it is complete, there should be an adequate CDF for all continuous distributions.

2017-04-20 08:07 UTC, springcoil reviewed
Looks cool to me. Good contributions. If you could add a few tests for infinite values that'd be cool. Otherwise we can leave it for another commit.

2017-04-20 08:07 UTC, springcoil commented on pymc3/tests/test_distributions.py
> +        # TODO: Check infinite values?
I would check infinite values. Seems a good check.

2017-04-20 08:09 UTC, springcoil commented
I guess we need to wait for Beta to get this to merge. But good work @domenzain :)

2017-04-22 18:09 UTC, fonnesbeck commented on pymc3/distributions/continuous.py
> +        value = value - alpha
use increment `value += alpha`

2017-04-22 19:54 UTC, ferrine requested changes
Does it all work with tensors, not scalars, we need more tests for that

2017-04-22 19:54 UTC, ferrine commented on pymc3/distributions/continuous.py
> +# TODO: Decide where to put this, or inline it everywhere it is used...
You can move it to `dist_math`

2017-04-22 19:54 UTC, ferrine commented on pymc3/distributions/continuous.py
> +        a = lam * float(value)
What if value is tensor? Mb `tt.as_tensor(value)` fits better there

2017-04-22 19:54 UTC, ferrine commented on pymc3/distributions/continuous.py
> +        return tt.switch(
Do you check vector value for this op?

2017-04-22 19:54 UTC, ferrine commented on pymc3/distributions/continuous.py
> +def normallogcdf(value, mu=0, sd=1):
Does it work with ndimentional tensors?

2017-04-24 11:47 UTC, domenzain reviewed
Latest review taken into account and integrated in commits where applicable.

2017-04-24 11:47 UTC, domenzain commented on pymc3/distributions/continuous.py
> +# TODO: Decide where to put this, or inline it everywhere it is used...
I don't know where to put this. I'm guessing there must be a more logical place than here.

2017-04-24 11:47 UTC, domenzain commented on pymc3/tests/test_distributions.py
> +        # TODO: Check infinite values?
I've pushed a quick explicit couple of tests.

2017-04-24 11:47 UTC, domenzain commented on pymc3/distributions/continuous.py
> +        return tt.switch(
I think all of these are element-wise operations.
When a tensor is passed as argument they would behave as expected:

```python
>>> tt.eq(np.array([1, 2, np.nan, -np.inf, np.inf]), np.inf).eval()
array([False, False, False, False,  True], dtype=bool)
```

2017-04-24 11:47 UTC, domenzain commented on pymc3/distributions/continuous.py
> +# TODO: Decide where to put this, or inline it everywhere it is used...
Done.

2017-04-24 11:47 UTC, domenzain commented on pymc3/distributions/continuous.py
> +def normallogcdf(value, mu=0, sd=1):
I'm unsure about broadcasting when the tensors will not be shaped identically.
But otherwise everything is element-wise ok.

2017-04-24 11:47 UTC, domenzain commented on pymc3/distributions/continuous.py
> +        a = lam * float(value)
Changing this. I'm using `floatX` and `as_tensor` instead.

2017-04-24 12:09 UTC, domenzain commented
I've removed `Beta` from this commit, seeing that @fonnesbeck is working on it directly on the target branch.

2017-04-24 12:37 UTC, fonnesbeck commented
@domenzain I was giving it a try, but have not finished yet.

Keep in mind, everyone, that this is being merged into a feature branch, so there will be another opportunity to review it before it is merged into master.

2017-04-24 12:38 UTC, fonnesbeck commented
@domenzain you may need to rebase your branch.

2017-04-24 16:47 UTC, fonnesbeck commented
I will merge this into my feature branch.

2017-04-24 16:47 UTC, merged