Upper lower
pymc-devs/pymc pull request #3424
Opened 2019-03-23 16:18 UTC by chang111

To fix the issue 3248

2019-03-24 00:31 UTC, chang111 commented
@junpenglao All check has passed. Please review it.

2019-03-24 08:00 UTC, lucianopaz requested changes
The commit history is a bit weird and shows all the commits you had done in your previous PR.

Nevertheless, you need to do 3 more things to get this done:
1. Add a line to the 3.7 release notes under maintenance specifying this fix.
2. Add tests to the test suite to explicitly test and ensure that the issue, #3248, is fixed and all potential values for the bounds work well.
3. Be careful about the `_normalization` function that relies on the bounds being `None` or not. You should change this to some `isinf` kind of control.

There was a previous PR, #3250, that did this but became stale and was never finished. You can look at it to get some ideas.

2019-03-24 08:00 UTC, lucianopaz commented on pymc3/distributions/continuous.py
> +        self.lower = tt.as_tensor_variable(floatX(lower)) if lower is not None else tt.as_tensor_variable(-np.inf)
You have to also `floatX` `np.inf`

2019-03-24 23:54 UTC, chang111 commented on pymc3/distributions/continuous.py
> +        self.lower = tt.as_tensor_variable(floatX(lower)) if lower is not None else tt.as_tensor_variable(-np.inf)
Thanks for your reply. I will check the pr 3250.

2019-03-25 12:24 UTC, twiecki commented
@chang111 Did you mean to close this?

2019-03-25 12:25 UTC, closed without merging