Fix for timeout in graph_model
pymc-devs/pymc pull request #3460
Opened 2019-05-03 21:52 UTC by rpgoldman

See #3458

2019-05-03 21:57 UTC, rpgoldman commented
This PR is *almost* right, I think, but somehow by changing the ancestor computation, I have changed the computation of the dimensions in graph rendering.

2019-05-04 09:40 UTC, lucianopaz requested changes
Given that you observed a change in the computed dimensions, could you add a new test to the test suite that checks if the computed dimensions match with what should be returned?

2019-05-04 09:40 UTC, lucianopaz commented on pymc3/model_graph.py
>          upstream = self._ancestors(var, func)
I would completely remove `self._ancestors` and replace it with the `stack_search` that you did

2019-05-04 12:32 UTC, rpgoldman commented
@lucianopaz actually the dimension change was not an issue in the breadth first search -- it revealed an error in the code I used to debug the search! That's a relief. I will see if I can propose some tests, but I don't understand the test suite  very well.
I will try to make the change you suggest today.

2019-05-04 14:10 UTC, rpgoldman commented
@lucianopaz I have just looked over the existing tests for the model grapher, and they check the structure, including the identification of plates.  So I think they are sufficient in their present form.  There is no obvious test to add based on the fix, because the old version didn't compute the wrong thing; it simply didn't complete. But I am open to suggestions.

Note: if this PR looks good, I should squash it before it's merged.

2019-05-05 07:50 UTC, lucianopaz requested changes
Everything looks fine to me. No other tests should be needed. Once `_ancestors` is removed, just add a line to the release notes under maintenance and the PR should be ready to merge

2019-05-05 07:50 UTC, lucianopaz commented on pymc3/model_graph.py
>          return set([j for j in ancestors([func], blockers=blockers) if j in self.var_list and j != var])
`_ancestors` now seems to be unused, right? If so, it should be removed.

2019-05-05 15:57 UTC, rpgoldman commented
@lucianopaz OK, I think this is done now.

2019-05-05 16:15 UTC, lucianopaz commented
Great! Thanks a lot @rpgoldman! Once the tests pass, I'll merge

2019-05-05 16:15 UTC, lucianopaz approved these changes

2019-05-05 16:17 UTC, lucianopaz requested changes
Oh, I had forgotten that you still need to add a line to RELEASE-NOTES.md under the maintenance section referencing the fixed issue

2019-05-05 16:55 UTC, rpgoldman commented
@lucianopaz Pushed the documentation and removed an unused import causing the check failure.

2019-05-05 19:04 UTC, merged

2019-05-05 19:05 UTC, lucianopaz commented
Thanks again @rpgoldman!

2019-05-05 19:49 UTC, rpgoldman commented
@lucianopaz No problem! I'm glad to be able to give even a little something back in exchange for all I've gotten from the community!

2019-05-06 08:12 UTC, twiecki commented
Thanks @rpgoldman!