remove previous instance of docker container in start_container script
pymc-devs/pymc pull request #3488
Opened 2019-05-22 14:41 UTC by Bruschkov

Checking out pymc3 the first time I noticed that the start_container script will crash, when a previous instance of the container already exists. Added two lines that will stop and remove an existing instance of the pymc3 container before building and running again.

This improves convenience and (as far as I can see) has no downsides.

2019-05-23 13:13 UTC, AustinRochford requested changes
I think these two lines will print errors in the case that a `pymc3` container does not already exist.  Could you add a check along the lines of

```bash
if [ ! "$(docker ps -q -f name=<name>)" ]; then
   # stop and remove
fi
```

(See https://stackoverflow.com/questions/38576337/how-to-execute-a-bash-command-only-if-a-docker-container-with-a-given-name-does)

to avoid that noise?

2019-05-23 13:15 UTC, Bruschkov commented
Yes, they do, but they get swallowed up really fast in the overall ouput of the script. You're right, though, that is not exactly clean... :-)

Will amend

2019-05-24 10:01 UTC, Bruschkov commented
Fixed the requested changes. Script now checks if container exists before shutting it down and removing it.

2019-05-24 13:19 UTC, twiecki commented
Needs a rebase, files are showing up in the diff that shouldn't.

2019-05-24 13:58 UTC, Bruschkov commented
> Needs a rebase, files are showing up in the diff that shouldn't.

Huh, sorry for that! I thought that I did... Rebased again, diff looking good now.

Cheers

2019-05-24 14:19 UTC, AustinRochford approved these changes

2019-05-24 14:19 UTC, merged

2019-05-24 14:19 UTC, AustinRochford commented
Thanks for this!