Expand posterior_predictive sampling docs
pymc-devs/pymc pull request #3517
Opened 2019-06-11 17:48 UTC by OriolAbril

PR to expand a little the documentation on sample_posterior_predictive and include one extra parameter to force the output to have shape `(nchains, ndraws, ...)`. 

I have already included tests for the new parameter, and modified the other posterior predictive tests that used `vars` parameter to use `var_names`

2019-06-11 18:02 UTC, rpgoldman requested changes
If we are doing this, we might as well fix the grammar.  It should be "the same shape AS..." not "the same shape of..."

2019-06-11 18:06 UTC, rpgoldman requested changes
Also, if `keep_size` interferes with `samples` and `size`, we should signal an exception if either of these arguments are specified when the caller specifies `keep_size` to be `True`, because the user is going to get something they don't expect.

2019-06-12 13:52 UTC, rpgoldman commented
👌!

Sent from my iPad

> On Jun 12, 2019, at 02:26, Thomas Wiecki <notifications@github.com> wrote:
> 
> Assigned #3517 to @rpgoldman.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-06-12 14:30 UTC, rpgoldman commented
@twiecki I'm happy to work to tweak this, but... what's our policy on how we emit warnings and exceptions?
Searching the source files I see that only the following files use logging:
```
backends/base.py
backends/report.py
tests/test_hmc.py
__init__.py
step_methods/hmc/base_hmc.py
sampling.py
variational/inference.py
parallel_sampling.py
```
From previous discussion, I believe that the policy is to emit warnings using the `warnings` library, not use the logger. I'm not sure what are the circumstances under which it's appropriate to use logging.
In this case, @OriolAbril, since the condition will occur only when the user *explicitly* supplies a contradictory set of arguments (accepting the defaults will not cause a conflict with `keep_size`) I believe we should at least emit a `UserWarning`.
I would _prefer_ we emit an error instead of a warning: the user is doing something very wrong here, and has a fundamental confusion about the arguments (or has made some kind of editing error).  
we should bring their attention to that fact, so that they fix the call to the sampler.  So I **strongly** prefer the use of some form of `Exception`, either a `ValueError` or, say, a `pm.IncorrectArgumentsError` that is a new subtype of `ValueError`.

2019-06-12 15:11 UTC, OriolAbril commented
Okey, thanks for the recommendations, I had no idea that `pm.IncorrectArgumentsError` existed. It seems quite appropriate. Is it okey to change the logging warnings for `samples` or `size` present when `keep_size` is true to a `pm.IncorrectArgumentsError` and leave the logging warning for `samples<nchains*ndraws` as it is? Or should it be modified to an `UserWarning` instance?

Also, I assume the clarifications about samples and size parameters are good to go.

2019-06-12 15:32 UTC, rpgoldman commented
> Okey, thanks for the recommendations, I had no idea that `pm.IncorrectArgumentsError` existed. 

Actually, it does not. I was suggesting that we add it.  I guess it would go into `exceptions.py` if we were to add it.

2019-06-12 15:41 UTC, rpgoldman commented
> Is it okey to change the logging warnings for `samples` or `size` present when `keep_size` is true to a `pm.IncorrectArgumentsError` and leave the logging warning for `samples<nchains*ndraws` as it is? Or should it be modified to a `UserWarning` instance?

I don't have a good answer to this, I'm afraid. On a previous PR I submitted, I was told to import `warnings` and use `warnings.warn`. If we were to do that, then yes, that warning should use `UserWarning`.

As my earlier question to @twiecki reflects, I don't know what policy this project has for logging.  There is very little use of logging in the source files I have seen -- it seems like some people have added logging, but most have not.  It seems like the backends code bundles up all the warnings and shoves them into the logger.  
So I believe we should just be using `warnings` and trusting that  code (in `backends/report.py`) to make sure that all the warnings get into the `pymc3` logger.  Would that be ok?

2019-06-17 21:57 UTC, merged