WIP: Optimize sample_posterior_predictive
pymc-devs/pymc pull request #3548
Opened 2019-07-16 18:40 UTC by rpgoldman

The previous implementation of `sample_posterior_predictive` was very slow, because it generated its samples pointwise.  This version generates the entire posterior predictive trace in a single pass over the graph.

Current status is pretty rough, and is missing support for the `size` argument.

2019-07-16 22:46 UTC, rpgoldman commented
There is still something wrong with this proposed fix.  Here is a file that shows a problem -- somehow my code is happy to sample from a random variable without examining its parents. Would appreciate any "eyes on" this.  You should be able to run this and see the assertion failure and the docstring at the top that shows how far I got trying to find the bug.
[test_spp.py.txt](https://github.com/pymc-devs/pymc3/files/3399378/test_spp.py.txt)

2019-07-16 23:02 UTC, rpgoldman commented
A quick follow-up to the above: in that test file, it seems I am able to sample from the normal distribution at `obs`, even though this value depends on the value of `beta`, which must be extracted from the trace:
```
(Pdb) p model['obs'].distribution.random()
array([ 9.23716427, 18.7427438 , 27.82220243])
```
My understanding is that this should *fail* with a missing input error when there is no `point` argument with a value for `beta`, because this is the model:
```
        y = pm.Data('y', [1., 2., 3.])
        beta = pm.Normal('beta', 0, 10.)
        pm.Normal('obs', beta * x, np.sqrt(1e-2), observed=y)
```
... and the code seems to expect this to fail also, so that the missing input error puts this variable onto the stack of variables to be evaluated in the context of the posterior trace.

2019-07-17 10:01 UTC, lucianopaz requested changes
I have one major concern regarding this PR: the `for` loop over the points in the trace is just being moved inside of `draw_value`. This will not removed the extra probabilistic graph trasversals that you are trying to avoid to increase sampling speed.

Each time you call a distribution's `random` method the following general scheme is ran:

```python
def random(self, point=None, size=None):
    parameters = draw_values(self.parameters, point=point, size=size)
    return random_variarate_sampler(parameters, some_size)
```

This means that you will start to have nested calls to `draw_values` trying to get each of the distribution's parameters. This will silently backtrace the probabilistic graphical model many times. Thanks to the caching done by the context manager, you wouldn't backtrace the full graph, but this already was already the case with the previous implementation of `sample_posterior_predictive`. So in the end, I don't see if there will be much of a performance gain with this.

The real comparison in sampling speed should be against `sample_prior_predictive`. Ideally, it should be __slower__ than `sample_posterior_predictive`, but it is usually faster because it relies on vectorized calls to the `random`. To really get `sample_posterior_predictive` to work fast, we need to exploit vectorization with the `size` argument of `draw_values`.

My other concern is that this PR introduces a huge of amount of duplicate code from `distribution.draw_values` and other functions therein. It should be possible to restructure the existing code to avoid this duplication.

2019-07-17 10:01 UTC, lucianopaz commented on pymc3/distributions/posterior_predictive.py
> +            return zip(range(samples), itertools.cycle(trace.points())) if trace \
Minor comments:
I think that it's safer to test if `trace is not None` and I also think it's better to split the lines using parenthesis

```python
return (
    zip(...)
    if trace is not None else
    zip(...)
)
```

2019-07-17 10:01 UTC, lucianopaz commented on pymc3/distributions/posterior_predictive.py
> +                        for i, point in conditional_iter():
This is a repeated comment. You are iterating through all the points and then calling `random`. This will retrace the graphical model at each iteration because of the nested `draw_values` calls in each `Distribution.random` method.

2019-07-17 10:01 UTC, lucianopaz commented on pymc3/distributions/posterior_predictive.py
> +                for i, point in conditional_iter():
This is a repeated comment. You are iterating through all the points and then calling `random`. This will retrace the graphical model at each iteration because of the nested `draw_values` calls in each `Distribution.random` method.

2019-07-17 10:01 UTC, lucianopaz commented on pymc3/distributions/posterior_predictive.py
> +                    for i, point in conditional_iter():
This is a repeated comment. You are iterating through all the points and then calling `random`. This will retrace the graphical model at each iteration because of the nested `draw_values` calls in each `Distribution.random` method.

2019-07-17 10:01 UTC, lucianopaz commented on pymc3/distributions/posterior_predictive.py
> +                        for i, point in conditional_iter():
This is a repeated comment. You are iterating through all the points and then calling `random`. This will retrace the graphical model at each iteration because of the nested `draw_values` calls in each `Distribution.random` method.

2019-07-17 10:01 UTC, lucianopaz commented on pymc3/sampling.py
> +        ppc_trace = posterior_predictive_draw_values(cast(List[Any], vars), trace, samples, size=size)
The progessbar is not used so the enclosing `try` and `except KeyboardInterrupt` can be removed.

2019-07-17 14:17 UTC, rpgoldman commented
> I have one major concern regarding this PR: the `for` loop over the points in the trace is just being moved inside of `draw_value`. This will not removed the extra probabilistic graph traversals that you are trying to avoid to increase sampling speed.

It is true that there were places I could not replace the `for` loop entirely, but I think this could later be done.  In places where it was easy for me to vectorize the generation I did that, but I did not have a sufficient understanding of the `random()` method to do it everywhere: hence my earlier questions about the "contract" of this method -- I didn't know where to find out (a) what its I/O behavior is or (b) what side effects it has.  For example, I did not understand that it is mutually recursive with `_draw_value()` until you pointed this out.

> 
> Each time you call a distribution's `random` method the following general scheme is run:
> 
```python
 def random(self, point=None, size=None):
     parameters = draw_values(self.parameters, point=point, size=size)
     return random_variarate_sampler(parameters, some_size)
```
I wish I had known this earlier....
> 
> This means that you will start to have nested calls to `draw_values` trying to get each of the distribution's parameters. This will silently backtrace the probabilistic graphical model many times. Thanks to the caching done by the context manager, you wouldn't backtrace the full graph, but this already was already the case with the previous implementation of `sample_posterior_predictive`. So in the end, I don't see if there will be much of a performance gain with this.

This suggests that what I need to do is to vectorize the `random()` method when I call it.  That I think is relatively straightforward.

More complicated is the fact that since `random()` and `get_values()` are mutually recursive, I need a mechanism to tell `random()` to invoke `PrePosteriorSampler.draw_value` rather than `_draw_value` in the posterior predictive context.  Since `random()` implementations are scattered through the code base, I'm not sure how this is to be done.  I suppose that I could override the definition of `_draw_value` so that instead of importing the original definition of `_draw_value` we get a version appropriately chooses between the two.
> 
> The real comparison in sampling speed should be against `sample_prior_predictive`. Ideally, it should be **slower** than `sample_posterior_predictive`, but it is usually faster because it relies on vectorized calls to the `random`. To really get `sample_posterior_predictive` to work fast, we need to exploit vectorization with the `size` argument of `draw_values`.

I mostly agree with this, but... the `size` argument of draw values in its current form does not interact correctly with the trace -- to vectorize fully efficiently I believe we need to modify the `random` argument

A complication with doing this is that the `size` argument of `draw_values` is distinct from, and confusingly interacts with the `size` argument of `sample_posterior_predictive`.  The latter enables us to generate multiple samples for a single point in the posterior trace.  This is incredibly complex because it affects allocating arrays for the return values -- instead of preallocating the return vectors (which I do to speed things up, instead of building big python lists and then converting them to arrays before return), we need to have array indices in the posterior predictive trace that are `size * samples` instead of just `samples`.  For now that was simply too complicated for me, and my PR does not support the `size` argument to posterior predictive sampling.

Put differently, the `size` argument to `_draw_value` tells it how many *iid* samples to generate.  But in order to speed this up, we need to draw values across the entire posterior trace, and those samples will *not* be iid in general, because they are conditioned on different values of the latent variables.



> My other concern is that this PR introduces a huge of amount of duplicate code from `distribution.draw_values` and other functions therein. It should be possible to restructure the existing code to avoid this duplication.

It *should* be, but I believe it is premature to do this.  It makes more sense -- at least to me -- to make this isolated version because it doesn't break other code.  The sampling code is incredibly complicated for a newcomer like me because there are un-articulated assumptions about duck-typing hidden in many calls to `hasattr`.

I believe it would be a lot better to continue with the duplicated code -- especially if there are assumptions in the original version of the code that cannot be honored in the vectorized version that I am building.  Then, once we see the full implications of the optimization, we can see how to properly remove duplicate code.

This gradualist approach has the above advantages from the point of view of engineering, but also is critically important to me, because my application **needs** fast posterior predictive sampling and I will have to be eating this dog food right away, rather than waiting for an elegant solution.

2019-07-17 15:46 UTC, lucianopaz commented
I had written a [small gist](https://gist.github.com/lucianopaz/eda06bc4d4ce8c28af8295156eb1f7bd) with an alternative implementation of the`sample_posterior_predictive` function that tries to vectorize the `draw_values` call across all the points in the trace. The solution relies on the new machinery put in place in `generate_samples` to handle batches of parameter values elegantly.
Consider sampling from the prior of the following model:

```python
with pm.Model():
    a = pm.Normal("a", 0, 1, shape=(3,))
    b = pm.HalfNormal("b", 1)
    c = pm.Normal("c", a, b, observed=np.random.rand(100))
```

Imagine you want to draw 10 samples from the prior. It's straightforward to draw 10 samples from `a` and `b`. The first is an array of shape `(10, 3)` and the second is an array of shape `(10,)`. What happens if you naively try to pass those arrays into scipy's normal rvs function? You get an error because the loc and scale parameters don't broadcast with each other. The way in which we solved this error, and many other variants of it, is to add new broadcasting rules, implemented in shape_utils.py. Namely, broadcasting is made aware that the first axes of arrays can hold iid draws of the RVs. By knowing the requested number of iid draws (the `size` parameter) we can identify said axes and ignore them for the broadcasting (what we do really is that we pad an appropriate number of axes to the right and then use numpy's normal broadcasting.

Imagine that for the same model we instead draw 10 samples from the posterior and then want to do posterior predictive sampling. If we want to vectorize the call, we have to pass all the parameter values held in the trace at the same time:

`point = {v: trace[v] for v in trace.varnames}`

The arrays of drawn values for each parameter will be the same as when we sampled from the prior, and to get `draw_values` to vectorize properly we just need to pass it an adequate `size` parameter. That's what I tried to do in the above gist.

2019-07-17 16:09 UTC, lucianopaz commented
I must add two more comments about the gist I shared above:

1. It completely ignores the original `size` parameter, but it could be adapted to use it.
2. It is not a are replacement of the original `sample_posterior_predictive` because most of the multivariate distributions have not been tested in the hierarchical setting and may run into more complicated shape errors than the ones addressed in shape_utils.py. There is a shape error in the issue tracker on `MvNormal` that illustrates the danger

2019-07-17 16:10 UTC, rpgoldman commented
*Note: the following post crossed with the last one from @lucianopaz, so may be obsolete.*

Here's an illustration of the issue with vectorizing the `random()` methods, taking the method from the `Uniform` distribution as an example:


```
    def random(self, point=None, size=None):
        """
        Draw random values from Uniform distribution.

        Parameters
        ----------
        point : dict, optional
            Dict of variable values on which random values are to be
            conditioned (uses default point if not specified).
        size : int, optional
            Desired size of random sample (returns one sample if not
            specified).

        Returns
        -------
        array
        """

        lower, upper = draw_values([self.lower, self.upper],
                                                    point=point, size=size)
        return generate_samples(stats.uniform.rvs, loc=lower,
                                                scale=upper - lower,
                                                dist_shape=self.shape,
                                                size=size)
```

If we want to pass a *trace* to this instead of a point, we can't do numpy vectorization because of the need to do the recursive draw_values, which is a point-wise operation, not trace-wise, and the traces are not vectorized pointwise but variable-wise.  And there's no computable transformation of arbitrary `random` methods (at least none that I can think of ), which holds out the threat of having to rewrite *every random method* to be vectorized.

This is what led me to just do the for loop when invoking `random`.  This still seems to be *much* faster than the old implementation, possibly just because I'm trying to build and fill numpy arrays, instead of building big lists and then converting them into numpy arrays after they are fully constructed.  This was still a non-trivial optimization because it requires more knowledge of the shape of the random variables.

With my latest fix the test in the attached `test_spp.py` file still fails, but now it fails by being not a good enough approximation to the target values.  I'm not sure how to track this down.  My guess is that the lookup is working better, but there's still something wrong, likely in the calls to `draw_values` in `random` methods.

2019-07-17 16:20 UTC, rpgoldman commented
Thanks!  I'll have another look at that.  I didn't realize that `generate_samples` was already doing what's necessary for vectorizing.

> Imagine that for the same model we instead draw 10 samples from the posterior and then want to do posterior predictive sampling. If we want to vectorize the call, we have to pass all the parameter values held in the trace at the same time:
> 
```python
point = {v: trace[v] for v in trace.varnames}
```
One question: why is this transformation needed?  The trace is already accessible through variable names to get the numpy arrays of sampled values, right?  So why can't we just pass `point=trace`?

Also:
> It completely ignores the original size parameter, but it could be adapted to use it.

I think the original size parameter for `sample_posterior_predictive` should be removed.  It requires the caller to think too hard, and makes for extremely messy code in the sampling.  When I did the looping to generate samples I just looped circularly over the posterior trace, which has the same effect, and doesn't require complex indexing in the sampled arrays or combining two dueling uses of `size`.

If we don't like this solution, for `samples > len(trace)` not too bad to just generate multiple posterior predictive samples and concatenate them.  The gain in code simplicity is worth it, in my opinion.

2019-07-17 16:24 UTC, rpgoldman commented
Here's the failing test result with my latest code:

```
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0.1
E       
E       Mismatch: 100%
E       Max absolute difference: 0.17832373
E       Max relative difference: 0.01989503
E        x: array([5, 6, 9])
E        y: array([5.101494, 6.118049, 9.178324])
```

This is almost worse than before -- before the results were crazy, but now they are just not as good as they should be.

2019-07-18 01:02 UTC, rpgoldman commented on pymc3/sampling.py
> +        ppc_trace = posterior_predictive_draw_values(cast(List[Any], vars), trace, samples, size=size)
Thanks; removed this.

2019-07-18 19:53 UTC, lucianopaz commented on pymc3/backends/base.py
> +        """Get sampler statistic0s from the trace.
```suggestion
        """Get sampler statistics from the trace.
```

2019-09-06 02:39 UTC, rpgoldman commented
Closing this, since it's superseded by #3597

2019-09-06 02:39 UTC, closed without merging