add ODE benchmarks
pymc-devs/pymc pull request #3730
Opened 2019-12-14 22:44 UTC by Dpananos

Solves  #3694

Should draw 3000 samples (1000 warm up in two chains) in approx 2.5 minutes, maybe a little quicker.  
I've tried to follow the example of `ExampleSuite`.  Let me know if I've missed something or if you prefer something else.

2019-12-16 14:37 UTC, michaelosthege requested changes

2019-12-16 14:37 UTC, michaelosthege commented on benchmarks/benchmarks/benchmarks.py
> +    timeout = 360
The timeout could be too tight

2019-12-16 14:41 UTC, Dpananos commented on benchmarks/benchmarks/benchmarks.py
> +    timeout = 360
Resolved by latest commit.

2019-12-16 16:01 UTC, michaelosthege commented
LGTM

2019-12-17 17:59 UTC, ColCarroll approved these changes

2019-12-17 17:59 UTC, merged

2019-12-17 18:00 UTC, ColCarroll commented
Thanks, @Dpananos -- the cloud benchmark machine is currently down, but I've been running on my laptop every week or so.