Conditionally disable fastprogress.progressbar in sample_posterior_predictive
pymc-devs/pymc pull request #3752
Opened 2019-12-30 17:43 UTC by rpgoldman

Instead of creating the progress bar and not displaying it, don't create it at all.

This allows users to avoid some display issues in console mode.

I did this before for sample, but missed its use here.

2019-12-30 23:51 UTC, michaelosthege requested changes
Hold on, the tests didn't catch it:

If `progressbar=False` and there are divergences, it blows up in line 634.

2019-12-31 00:00 UTC, rpgoldman commented
Thanks, @michaelosthege , I see the problem -- we need to make sure that the progress bar is there before writing to its comment field.

Here's a question -- is there a good way I could create a test for this? Do you have a simple model with a divergence I could put in the tests?

2019-12-31 00:17 UTC, michaelosthege commented
`_pbar_data` is always defined, so you can drop line 622 and the corresponding condition in 633.

The model from @twiecki's blog post about funnels could give divergences.

2019-12-31 17:36 UTC, rpgoldman commented
> `_pbar_data` is always defined, so you can drop line 622 and the corresponding condition in 633.

Thanks for the simplifications.  I applied them, and then did a pass of style cleanups (pylint, black, pydocstyle).

2019-12-31 20:54 UTC, rpgoldman commented
@michaelosthege Would you please have one more look at this, and squash merge if it's ok? I think I have made all the changes you suggested, and done some clean-up, as well.

2020-01-01 12:45 UTC, michaelosthege requested changes
Did you use black for the formatting?
In my opinion there are a lot of unnecessary line breaks - probably due to a very conservative line length.

I'll go and edit a few strings.

2020-01-01 12:45 UTC, michaelosthege commented on pymc3/sampling.py
> +    r"""Draw samples from the posterior using the given step methods.
Why this `r`-string? Does it have to do with doc formatting?

2020-01-01 12:45 UTC, michaelosthege commented on pymc3/sampling.py
> +        """Start a separate process to perform stepping of a chain.
No, this is wrong.
Should be: `This method is started on a separate process...`

2020-01-01 12:59 UTC, michaelosthege commented
The target coverage check failed, probably because line breaks in warnings increased the total number while not being covered by tests.

As much as I dislike vertically stretched out code, I also think that it's now technically fine.
So if everybody agrees we can merge even though it decreases coverage.

2020-01-01 16:01 UTC, rpgoldman commented
The vertically stretched out code, FWIW, isn't really me: it's formatting by black, which I believe to be the project standard.

Thanks for so carefully reviewing this.

2020-01-01 16:07 UTC, michaelosthege commented
Our `.pylintrc` already specifies a maximum line length of 100, which would allow most of these changes to be on one line.

How did you run the `black` command? Maybe we need to specify some settings somewhere (I'm not familiar with it yet).

2020-01-01 16:19 UTC, michaelosthege commented
From [blacks README](https://github.com/psf/black/blob/master/README.md), this should do the trick:

`black --line-length 100`

Their default is 88, so...

2020-01-02 20:22 UTC, rpgoldman commented
@michaelosthege When you get a chance, will you please look at the results of my re-running black with line length of 100?

I think this fixes the things you didn't like. Please let me know, and I will get this tidied up a little (I will try to separate the reformatting from the progress bar disabling) and merged.

2020-01-03 04:17 UTC, merged