add Apache license to every python files
pymc-devs/pymc pull request #3781
Opened 2020-01-20 14:35 UTC by rushabh-v

Fixes: #3738

2020-01-20 14:48 UTC, rushabh-v commented
I actually wrote a python script to add the license to all the .py files at once. So it also doesn't need much deeper sanctioning I think.

I have also cross-checked by looking at how many total .py files are there in this repo using the language bar of this repo. The language bar says there are 159 python files and this commit has changed 160 files. So I think there wouldn't be any problem.

2020-01-20 15:09 UTC, rushabh-v commented on pymc3/ode/utils.py
> -        The sensitivity matrix will always have consistent form. (n_states, n_states + n_theta)
The 113 deletions it says are not actually deletions, probably an error in git. Because the lines are just deleted and then added back.

2020-01-20 18:08 UTC, rushabh-v commented
@eigenfoo Can you review this, please?

2020-01-20 22:57 UTC, eigenfoo requested changes
This looks great @rushabh-v! Unfortunately I think we shouldn't be licensing the documentation or the examples: a few of them are actually taken or adapted from other projects or resources and already provide relevant credits, and I'd prefer not to license them as our own code. (For instance, the baseball example is taken from the Stan user guide.)

So, to be explicit: the `.py` files under the `docs/` and `pymc3/examples/` directory should not have the license comments.

2020-01-21 01:44 UTC, rushabh-v commented
@eigenfoo

2020-01-21 17:10 UTC, rushabh-v commented
@eigenfoo can you review the latest changes, please?

2020-01-23 00:16 UTC, eigenfoo reviewed
This PR looks good to me but I'm pretty shocked that codecov reports our coverage as decreasing by 20%. That definitely can't be the case (this PR only adds comments), so I'm wondering what's going on here. @lucianopaz can you advise?

2020-01-23 02:24 UTC, rushabh-v commented
Actually when I pushed the last commit firstly the xodecov report said that this PR will increase the convergence by 0.01%. And then suddenly the report got changed. Can you check your mail if you have subscribed to this PR?
![see the screenshot of mine](https://user-images.githubusercontent.com/46084304/72951734-7e909180-3db5-11ea-939f-53099a32193a.jpg)

2020-01-23 02:27 UTC, rushabh-v commented
Should I try pulling upstream and pushing again?

2020-01-23 10:06 UTC, lucianopaz commented
😬

@eigenfoo, I tried to review the report uploading process in travis-ci's logs, but the `after_success` script output seems to be hidden so I can't tell if there was a communication error. However, I partly reviewed the [uploaded bundles](https://codecov.io/gh/pymc-devs/pymc3/commit/2623aa863b795df7520cda9be932562df6baf9ce/build) and at least they seem to show accurate coverage values for the tests that travis should have run in each environment. The problem is that I can't say for certain if the coverage for the rest of the project is ok, because, unlike with pymc4, we aren't specifying the `--cov-report term` to `pytest` when we [call it](https://github.com/pymc-devs/pymc3/blob/master/scripts/test.sh#L10), so travis doesn't print out a summarized coverage of each build to the terminal.
At this point, I'm inclined to ask for support over at [codecov](https://docs.codecov.io/docs/unexpected-coverage-changes), but maybe @rushabh-v, you could add `--cov-report term` at the end of [this line](https://github.com/pymc-devs/pymc3/blob/master/scripts/test.sh#L10) and push the changes so this PR rebuilds and we can see if the problem is codecov or pytest-cov's fault.

2020-01-23 10:20 UTC, lucianopaz commented
Actually, this is definitely a codecov problem. The coverage for [test files](https://codecov.io/gh/pymc-devs/pymc3/tree/2623aa863b795df7520cda9be932562df6baf9ce/pymc3/tests) are completely wrong. It looks like the multiple report files weren't merged together. I'll wait to see what happens with the current build, but lets hope that codecov doesn't skrew up this time. 🤞

2020-01-23 11:25 UTC, lucianopaz commented
Great work @rushabh-v!

2020-01-23 11:25 UTC, merged

2020-01-23 12:49 UTC, eigenfoo commented
Thanks for digging into this @lucianopaz! And congrats on the PR, @rushabh-v!

2020-01-23 15:32 UTC, rushabh-v commented
Thanks :)

2020-01-23 15:36 UTC, rushabh-v commented
Shouldn't we remove `--cov-report term` from test.sh or is it okay? @lucianopaz

2020-01-23 16:26 UTC, lucianopaz commented
@rushabh-v, I prefer that we leave that in. It would have helped me when I tried to review the build status on Travis, and I also think that it's helpful while building locally.