allow pymc3.Data() to support both int and float input data
pymc-devs/pymc pull request #3816
Opened 2020-02-26 10:31 UTC by hottwaj

Previously all input data was coerced to float when passed to pymc3.Data()

Attached changes implement this behaviour:

1. use dtype of passed array, if it has a dtype attr
2. otherwise test if input data is instance of int
3. otherwise assume float

WIP for #3813

2020-02-26 12:25 UTC, AlexAndorra requested changes
Thanks @hottwaj -- looks like a great start! 
Just a thought a first glance: I tend to think that np.int8 and np.int16 should be accepted (or at least cast to np.int32). Otherwise, in the current implementation these will raise a `ValueError('Unsupported type')`, while in fact they are types we want to support. Makes sense?
And I'm sure @rpgoldman will have valuable feedback!

2020-02-26 18:24 UTC, rpgoldman commented
I think we should add tests to `tests/test_data_container.py` and not just check that the data creation works properly, but also verify that we can use `set_data()`, as well.

2020-02-28 10:10 UTC, hottwaj commented
Thanks guys, will make those changes when I have time over the next few days.

2020-03-12 18:34 UTC, AlexAndorra commented
Hey @hottwaj and @rpgoldman ! Do you know where we are on this? Not trying to be pushy, just being curious -- 😄

2020-03-12 21:18 UTC, hottwaj commented
Hi sorry I'm on holiday this week and will be a bit more pushed for time
for next couple of weeks once I'm back at work. Best assume it might be a
few more weeks before I can finish off. Hope that's OK, thanks!

On Thu, 12 Mar 2020, 19:34 Alexandre ANDORRA, <notifications@github.com>
wrote:

> Hey @hottwaj <https://github.com/hottwaj> and @rpgoldman
> <https://github.com/rpgoldman> ! Do you know where we are on this? Not
> trying to be pushy, just being curious -- 😄
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pymc-devs/pymc3/pull/3816#issuecomment-598352993>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABK6JBNGSVGMQUYLN7VAKQLRHETLRANCNFSM4K4BZMNA>
> .
>

2020-05-11 18:14 UTC, AlexAndorra commented
Hi @hottwaj ! Do you think you'll be able to find some time to finish up this PR? Or do you need me to take over?
The 3.9 release is approaching and it'd be nice to ship it with this new feature 😃

2020-05-12 06:49 UTC, hottwaj commented
Hi Alex, sorry for not making any further progress...  Between work and childcare things have been difficult since the UK went into lockdown!  I am still a bit too busy to set aside time for this in the short term, feel free to take over and I hope the little I did was useful...  If you end up parking it for a bit longer let me know and I can hopefully revisit in another couple of weeks.  Thanks!

2020-05-12 08:03 UTC, AlexAndorra commented
I completely understand @hottwaj, the last couple of weeks have indeed been difficult. I'll take this PR over then, and try to push it through for 3.9 😉 
Thanks for the work you did, it's definitely helpful! Good luck for the coming weeks and stay safe 😷

2020-05-12 08:45 UTC, hottwaj commented
Great thanks, and hopefully I said this before but thanks for your work on this awesome tool!

2020-05-17 18:48 UTC, AlexAndorra commented
Closing in favor of #3925

2020-05-17 18:48 UTC, closed without merging