Check that concentration parameters of Dirichlet distribution are all > 0
pymc-devs/pymc pull request #3853
Opened 2020-03-25 18:05 UTC by AlexAndorra

As dicussed with @junpenglao, the Dirichlet distribution doesn't check that the concentration parameters (`a` vector) are all strictly positive when the distribution is initialized. 

Currently, the user can define `pm.Dirichlet("p", a=np.array([-1, 2, 3]), shape=3)` in a model and PyMC won't complain before the user tries to sample from the model (`BadInitialEnergy Error`).

As the concentration parameters *have* to be > 0, this PR just checks that it is the case before the user can do anything else.
Thanks in advance for the review, and I'm there for any comment/change. PyMCheers ✌️

2020-03-27 13:58 UTC, AlexAndorra commented
I'm not sure I understand CodeCov output here: does this mean I have to modify something in all of the mentioned "Impacted files"?

2020-03-27 18:46 UTC, twiecki commented
Does it work if the input is a RV?

2020-03-27 18:48 UTC, ColCarroll commented
This looks like just a buggy report. I wouldn't worry.

2020-03-27 18:48 UTC, ColCarroll commented
(note: thomas' question is still a good one)

2020-03-27 18:51 UTC, AlexAndorra commented
Thanks @ColCarroll -- kind of a relief 😅 
@twiecki, do you mean if the `a` vector is a probability distribution?

2020-03-27 18:57 UTC, twiecki commented
Yes, exactly.

2020-03-27 19:04 UTC, AlexAndorra commented
The condition I added to check _strict_ positiveness is only for arrays -- so no; I should add this case. I suppose positiveness is already taken care of; I just have to figure out how to add the "strict" 😉

2020-03-28 17:32 UTC, AlexAndorra commented
Still getting esoteric CodeCov warnings, but the tests passed 🎉 
Turns out the strict positiveness was a problem only when `a` was _not_ an RV, so I restricted the check to only those cases.
I'll also enabled the possibility to specify `a` as a list in addition to a numpy array, and I added some checks on `a`'s type.
Happy to hear what you guys think 🖖

2020-03-29 09:23 UTC, twiecki commented
@AlexAndorra A test would be good.

2020-03-29 10:28 UTC, AlexAndorra commented
Is think there already are tests, aren't there? In `test_distributions.py` and `test_distributions_random.py`

2020-03-30 06:30 UTC, twiecki commented
@AlexAndorra Apparently not of passing in negative values, otherwise that test would have failed I think.

2020-03-30 08:51 UTC, AlexAndorra commented
Ow ok -- sorry I'm not well versed in testing.
Very busy this week but I'll take a look ASAP!

2020-04-01 18:30 UTC, twiecki commented
```
=================================== FAILURES ===================================
_________________ TestMatchesScipy.test_dirichlet_init_fail[3] _________________
self = <pymc3.tests.test_distributions.TestMatchesScipy object at 0x7f441e645c88>
n = 3
    @pytest.mark.parametrize('n', [3, 4])
    def test_dirichlet_init_fail(self, n):
        with Model():
            with pytest.raises(ValueError) as err:
                _ = Dirichlet('x', a=np.zeros(n), shape=n)
>           err.match("All concentration parameters (a) must be > 0.")
E           AssertionError: Pattern 'All concentration parameters (a) must be > 0.' does not match 'All concentration parameters (a) must be > 0.'
pymc3/tests/test_distributions.py:959: AssertionError
_________________ TestMatchesScipy.test_dirichlet_init_fail[4] _________________
self = <pymc3.tests.test_distributions.TestMatchesScipy object at 0x7f4415c37f28>
n = 4
    @pytest.mark.parametrize('n', [3, 4])
    def test_dirichlet_init_fail(self, n):
        with Model():
            with pytest.raises(ValueError) as err:
                _ = Dirichlet('x', a=np.zeros(n), shape=n)
>           err.match("All concentration parameters (a) must be > 0.")
E           AssertionError: Pattern 'All concentration parameters (a) must be > 0.' does not match 'All concentration parameters (a) must be > 0.'
pymc3/tests/test_distributions.py:959: AssertionError
```

2020-04-01 19:03 UTC, lucianopaz requested changes

2020-04-01 19:03 UTC, lucianopaz commented on pymc3/tests/test_distributions.py
> +            err.match("All concentration parameters (a) must be > 0.")
```suggestion
            err.match(r"All concentration parameters \(a\) must be > 0.")
```

Parenthesis are a special character in regular expressions so you have to escape them with a backlash in the `match`

2020-04-01 19:03 UTC, lucianopaz commented on pymc3/tests/test_distributions.py
> +            err.match("All concentration parameters (a) must be > 0.")
```suggestion
            err.match(r"All concentration parameters \(a\) must be > 0.")
```

Parenthesis are a special character in regular expressions so you have to escape them with a backlash in the `match`

2020-04-01 19:03 UTC, lucianopaz commented on pymc3/tests/test_distributions.py
> +            with pytest.raises(ValueError) as err:
You can pass a `match` kwarg in the `pytest.raises` context manager and avoid storing it as `err` and later calling the `match` method. You can look at the [pytest docs](https://docs.pytest.org/en/latest/assert.html#assertions-about-expected-exceptions)

2020-04-01 20:19 UTC, AlexAndorra commented
Thanks guys, this was very helpful!

2020-04-03 16:02 UTC, merged

2020-04-03 16:02 UTC, twiecki commented
Thanks!