Expand pm.Data capacities
pymc-devs/pymc pull request #3925
Opened 2020-05-17 18:42 UTC by AlexAndorra

This PR expands on @hottwaj's work in #3816. Now, `pm.Data` can:
- Be used with integers as well as floats, which allows using it for index variables:
```python
with pm.Model() as model:
    index = pm.Data('index', np.array([2, 0, 1, 0, 2]))
    alpha = pm.Normal('alpha', 0, 1.5, shape=3)
    pm.Normal('obs', alpha[index], 1., observed=y)
```
- Be fed as input to other RVs, as asked in #3842:
```python
with pm.Model():
    x = pm.Data("x", [1.0, 2.0, 3.0])
    y = pm.Normal("y", mu=x, shape=3)
```
This is ready for review -- thanks a lot in advance for the reviews 🖖 

+ [ ] No breaking changes (that I know of)
+ [ ] Changes are covered by tests and docstrings
+ [ ] Mentioned in the RELEASE-NOTES.md

2020-05-17 20:33 UTC, lucianopaz requested changes
Great work @alexandorra! I left some comments throughout the changed you made. What I think is the most important point that should be addressed is the default dtype. I think that it should be `theano.config.floatX`for floats and the corresponding `intX` dtype for ints. You can take a look at our `intX` function to find the mapping that we use to set the integer dtype based on theano's floatX.

2020-05-17 20:33 UTC, lucianopaz commented on RELEASE-NOTES.md
> +- `pm.Data` container can now be used for index variables, i.e with integer data and not only floats (see [#3925](https://github.com/pymc-devs/pymc3/pull/3925)).
Could you also link both of these to the corresponding issues?

2020-05-17 20:33 UTC, lucianopaz commented on pymc3/data.py
> +                dtype = int
It would be better to default to whatever `intX` would be instead.

2020-05-17 20:33 UTC, lucianopaz commented on pymc3/data.py
> +                dtype = float
It would be better to default to theano's `floatX`

2020-05-17 22:56 UTC, michaelosthege approved these changes

2020-05-17 22:58 UTC, michaelosthege commented
I have nothing to add - Lucianos point on intX/float is important and the rest looks good 👍

2020-05-18 10:22 UTC, AlexAndorra commented
Thanks for the reviews @lucianopaz and @michaelosthege ! 
Actually, while trying to implement Luciano's suggestions, I realized, quite surprisingly, that no type setting was needed to implement the "`pm.Data` as index variables" feature. Even more, explicitly setting the type with `floatX` and `intX` was failing everything 😮
You can see that in the updated code and tests -- please tell me if I'm mistaken because I'm really surprised by that result. Otherwise, I think this is ready to merge 😊

2020-05-18 10:47 UTC, michaelosthege commented
> Thanks for the reviews @lucianopaz and @michaelosthege !
> Actually, while trying to implement Luciano's suggestions, I realized, quite surprisingly, that no type setting was needed to implement the "pm.Data as index variables" feature. Even more, explicitly setting the type with floatX and intX was failing everything 😮
> You can see that in the updated code and tests -- please tell me if I'm mistaken because I'm really surprised by that result. Otherwise, I think this is ready to merge 😊

You mean the pipeline for commit 0d07347 ?

It fails on a test that doesn't sound related:
`FAILED pymc3/tests/test_model_helpers.py::TestHelperFunc::test_pandas_to_array`

2020-05-18 14:16 UTC, AlexAndorra commented
Ok, this was more complicated than I expected, but I think I understood the problem and figured out a more parcimonious implementation in the process. Tests pass locally -- if they pass on Travis too, this means it's ready for review 🍾

2020-05-18 14:53 UTC, michaelosthege approved these changes

2020-05-18 15:08 UTC, lucianopaz approved these changes
Great catch @AlexAndorra!

2020-05-18 15:08 UTC, merged