rewrite radon notebook using ArviZ and xarray
pymc-devs/pymc pull request #3963
Opened 2020-06-14 03:00 UTC by OriolAbril

I am in the process of rewriting the notebook to exploit all ArviZ and xarray goodness. Comments are very welcome and I hope it is useful as a way to showcase xarray mostly and ArviZ capabilities inherited from xarray. 

Depending on what your PR does, here are a few things you might want to address in the description:
+ [x] important background, or details about the implementation
  - Doing this I have encountered a couple bugs in ArviZ so this notebook won't even run on ArviZ master, only on PR branch. I am not sure about the timeline of the doc sprint but it will end up either running on ArviZ master or on next release (there may be a release coming in the coming weeks :thinking:)
+ [ ] consider adding/updating relevant example notebooks
+ [ ] right before it's ready to merge, mention the PR in the RELEASE-NOTES.md

2020-06-15 21:52 UTC, OriolAbril commented
I think that the part that has already been updated is ready for review, I hope all xarray tricks are clear and do not seem too obfuscating. Please comment on explanations being too little (or too much) detailed, names used (variables, coordinates, dimensions...), all comments will be welcome

2020-06-16 20:23 UTC, AlexAndorra commented
Just did a quick skim and this is looking really nice @OriolAbril 👌 Will do a complete review later this week.
This NB is definitely gonna enter our hall of fame 😉

2020-06-17 02:26 UTC, ColCarroll commented
this looks awesome oriol! i'm also excited about alex's change, with the `return_inferencedata=True`. 

A note I don't feel strongly about, but can make the cells a little cleaner: if you `np.random.set_seed(42)` at the start of the notebook, it should be reproducible, so long as you are using the same number of chains at each step and you run the notebook in order. This can lower the clutter of passing a `RANDOM_SEED` at every sample call.

2020-06-17 09:47 UTC, AlexAndorra requested changes
Ok, did a complete review! Lots of good stuff in there. I had some comments and questions that you'll find below but that shouldn't be too much work 😉 Tell me if anything is unclear!

2020-06-17 09:51 UTC, AlexAndorra commented
<p>This is a nerdy reference to "<a href="https://en.wikipedia.org/wiki/Flash_(comics)" target="_blank">The Flash</a>", so no lowercase required ;)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-17 09:51 UTC, AlexAndorra commented
<p>Yeah, the white space is from ReviewNB. I think they do that do that to ease comparison within cells, but I find it's not yet optimal</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-17 17:13 UTC, OriolAbril commented
<p>There is only one line between model context and plotting, the rest are reviewNB artifacts</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-17 17:14 UTC, OriolAbril commented
<p>Maybe I should upercase "The" then? </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-17 21:12 UTC, OriolAbril commented
<p>yep, I was waiting until merging the fix for automagical coords (otherwise I would have had to update the code to use return inferencedata and inferencedata kwargs and then again to remove the kwargs)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-17 21:28 UTC, OriolAbril commented
<p>used to (due to bug in ArviZ), I am updating this so I'll mark as resolved :)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-17 21:36 UTC, OriolAbril commented
<p>I think this will give more context into xarray which will ease the application of these techniques to different (but still somewhat similar) analylsis. I would not oppose to removing it though. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-17 22:02 UTC, OriolAbril commented
<p>I want to leave this for 2 motives:</p><p> </p><ul><li>albeit conceptually more convoluted, this is only 1 line more of code (labels are automatic this this and therefore there is not need to set xticklables nor xlabel anymore)</li><li>I do want to encourage it. This is adding a coordinate to the observed_data group -- which can then be used at any time! It is not the case here, but if we had 4 plots instead of 1 we could remove manual setting of xticklabels and xlabel for all 4 of them.</li></ul><p> </p><p>I am moving it to its own cell above to explain what is happening and why.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-17 23:13 UTC, OriolAbril commented
<p>Yes! I am updating all calls to use <code>return_inferencedata</code>  <strong>and</strong> automatic coords and dims</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-17 23:15 UTC, OriolAbril commented
<p>Glad it helps! :)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-17 23:16 UTC, OriolAbril commented
<p>Not really sure, I assumed it was for aesthetical reasons</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-18 01:19 UTC, OriolAbril commented
I have rewritten the whole notebook, but even if there were no extra review comments, it is not yet ready to merge!

I will rerun the notebook in sequential order once the related ArviZ PRs have been merged, the notebook as it is needs the two unmerged PRs to run correctly.

2020-06-18 07:59 UTC, AlexAndorra commented
<p>It's your call honestly. If you keep everything though, maybe emphasize the <code>input_core_dims</code> stuff, and talk about the rest as context?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-18 08:01 UTC, AlexAndorra commented
<p>I agree it's a good educational opportunity. Moving it to its own cell above to explain what is happening and why is the right thing to do IMO</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-18 08:04 UTC, AlexAndorra commented
<p>It's to make the difference in effects of level on radon apparent. Otherwise, just with the scatter points, you can't easily see the two mean effects and the surrounding uncertainty</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-18 08:06 UTC, AlexAndorra commented
<p>Good idea. This issue is on my to-do list and I hope to get it done in the coming weeks...</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-18 10:34 UTC, OriolAbril commented
<p>It governs how the chain number affects the plotted lines. The default for <code>compact</code>  is <code>chain_prop=("ls", ("-", "--", ":", "-."))</code>  which makes each line have a different linestyle.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-18 10:41 UTC, AlexAndorra commented
<p>Ah nice, didn't know about that!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3963/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2020-06-18 11:38 UTC, OriolAbril commented
I am having some issues with reviewNB so I'll comment here:

![image](https://user-images.githubusercontent.com/23738400/85015660-9d2e6500-b168-11ea-8dfd-8b54e17cbe83.png)


This plot is the one with most differences between previous version and current implementation -- I strived to make all plots look exactly the same as the original. That is because the implementation is actually different:
* Original nb: averages `a` and `a_county` and then adds
* Current version: adds `a` and `a_county` and then averages

Not sure if this is worth mentioning in the notebook, i.e. something along the lines of how seamless it is to average the desired dimensions after all calculations have been done now that we don't have to care about broadcasting rules.

2020-06-18 13:14 UTC, AlexAndorra commented
Do you mean that the _results_ are different, or the _code_ to get them is? In the first case that'd be a problem because it would mean weren't computing the same quantity. In the case, it's fine and well worth highlighting that we don't have to care about broadcasting and shape handling with xarrays 👌

2020-06-18 14:08 UTC, OriolAbril commented
_results_ are different! Sorry I was not clear enough and I can't get reviewNB to show the same cell side by side so it is difficult to see the differences.

As I was saying above, the original approach was to average first, operate afterwards. This therefore assumes that the expected value of an operation is the operation applied to the expected values of the operands. This is true for sums (and therefore correct for `covariation_intercept_slope` as we are only adding `a+a_county` or `b+b_county`) but does not always hold for products (and therefore does not hold for `varying_intercept_slope` as `a + za_county * sigma_a` does not take into account the covariance between `za_county and sigma_a`). If you pay a lot of attention to the 2 plots you'll see that the black dots are at the same positions but the blue ones are not.

TL;DR: yes, results are different because they should be due to an averaging mistake.

2020-06-18 16:30 UTC, AlexAndorra commented
Very clear, thanks 👌 And I realize I wasn't very clear either 😅 
In short, I agree that we should totally operate first and aggregate second

2020-06-21 16:23 UTC, kyleabeauchamp commented
Looks like there's a lot of verbosity in the cells displaying the xarray objects, might want to suppress those outputs for brevity.

2020-06-21 21:06 UTC, OriolAbril commented
> Looks like there's a lot of verbosity in the cells displaying the xarray objects, might want to suppress those outputs for brevity.

@kyleabeauchamp I guess you are talking about the html repr which is not rendered by github, the raw text is really long, but it is hidden and can be shown interactively, here is a proper render: https://nbviewer.jupyter.org/github/OriolAbril/pymc3/blob/radon_nb/docs/source/notebooks/multilevel_modeling.ipynb

2020-06-28 23:35 UTC, OriolAbril commented
I think I have addressed all comments so far, do not hesitate to complain if I missed some comment. I have reexecuted the nb on pymc 3.9.2 and ArviZ 0.9.0 so I think everything is ready to merge now unless there are still more reviews coming which will always be very welcome

2020-06-29 08:55 UTC, AlexAndorra commented
Ha ha I have one last nitpick comment: I think `import seaborn as sns` can be removed now, as it's no longer used in the NB

2020-06-29 15:45 UTC, OriolAbril commented
Should this be added to release notes?

2020-06-29 15:58 UTC, AlexAndorra commented
I think so, it's a pretty big revamp, so it's good to publicize it 😉

2020-06-29 17:45 UTC, AlexAndorra approved these changes
Thanks a lot @OriolAbril, all looks awesome now 🎉 I'm in love with this notebook 💘

2020-06-29 17:45 UTC, merged