Fix pymc3 to work with latest theano-pymc master
pymc-devs/pymc pull request #4382
Opened 2020-12-25 07:09 UTC by kyleabeauchamp

The current pymc master branch is pinned to the latest theano release, but there have been some breaking changes since that release (e.g., Random and jax_dispatch changes).  This PR fixes these compatibility issues.

2020-12-25 10:35 UTC, twiecki commented
There is a Theano-PyMC 1.0.13 which you can try to pin.

2020-12-25 17:21 UTC, kyleabeauchamp commented
Several of the remaining test failures seem like a possible regression in theano or pymc3 somewhere.  The following one pops up in several locations, and there are a few other pickle-related failures as well:

```
    def test_model_roundtrip(self):
        m = self.model
        for proto in range(pickle.HIGHEST_PROTOCOL + 1):
            try:
>               s = pickle.dumps(m, proto)
E               AttributeError: Can't pickle local object 'add_compile_configvars.<locals>.<lambda>'
```

2020-12-25 23:14 UTC, twiecki commented
CC @michaelosthege @brandonwillard

2020-12-26 18:47 UTC, twiecki commented
@kyleabeauchamp Were you able to test with https://github.com/pymc-devs/Theano-PyMC/pull/242 ?

2020-12-26 18:51 UTC, kyleabeauchamp commented
I haven't tested, sorry.  I tried to edit requirements.txt and trigger CI/CD but I don't think that works because we're using an environment install path that doesn't support direct git access.

2020-12-26 18:54 UTC, twiecki commented
@kyleabeauchamp Maybe you can just run the failing test locally?

2020-12-26 19:07 UTC, kyleabeauchamp commented
I can confirm that `pytest -v pymc3/tests/test_pickling.py` is now working with the theano-pymc PR, so that PR does fix some things.  The remaining tests are running now.

2020-12-27 02:45 UTC, kyleabeauchamp commented
Looking at local tests, there are some other tests failing as well.  You can see them in the CI/CD logs too if you look.  

```
self = <theano.compile.ops.Rebroadcast object at 0x7faa084385b0>, x = normal_rv.out

    def make_node(self, x):
        if self.axis.keys() and (x.ndim <= max(self.axis.keys())):
>           raise ValueError("Trying to rebroadcast non-existent dimension")
E           ValueError: Trying to rebroadcast non-existent dimension

Theano-PyMC/theano/compile/ops.py:719: ValueError
[...]
FAILED pymc3/tests/test_sampling.py::TestSample::test_sample_init - ValueError: Trying to rebroadcast non-existent dimension
FAILED pymc3/tests/test_sampling.py::test_exec_nuts_init[advi] - ValueError: Trying to rebroadcast non-existent dimension
FAILED pymc3/tests/test_variational_inference.py::test_replacements_in_sample_node_aevb[NormalizingFlowGroup: {'flow': 'scale'}] - ValueError: Trying to rebroadcast non-existent dimension
[...]
```

2020-12-27 10:22 UTC, twiecki commented on requirements.txt
> +theano-pymc==1.0.13
```suggestion
theano-pymc==1.0.14
```

2020-12-27 10:27 UTC, twiecki commented
/pre-commit

2020-12-27 10:28 UTC, twiecki commented
/pre-commit-run

2020-12-27 11:44 UTC, michaelosthege commented
I'm looking into https://github.com/pymc-devs/Theano-PyMC/issues/243

It would be great if either of you can already deal with the `DeprecationWarning: Function change_flags is now deprecated! Use theano.config.change_flags instead!` on this branch.

2020-12-27 14:10 UTC, michaelosthege commented
Looks like the switch from `theano.sandbox.rng_mrg.MRG_RandomStreams` to `theano.tensor.random.utils.RandomStream` blew it up.
The two interfaces seem to be not completely identical. I'm not sure who's to blame or on which side it should get fixed. Waiting for input from @brandonwillard.

2020-12-27 20:51 UTC, brandonwillard requested changes
Some&mdash;if not all&mdash;of the current errors are due to `pymc3.variational.opvi`'s use of Theano's old broken RNG interface.

Specifically, lines like [this](https://github.com/pymc-devs/pymc3/blob/3cfee77fda041483e86d9c61fa1d1ada9380cdb3/pymc3/variational/opvi.py#L1081) wrongly assume that the first argument to an RNG sampler is always the output size/shape.  This is&mdash;and was&mdash;incorrect according to the NumPy interface Theano's RNGs were supposed to emulate, and the new interface fixed that, so it absolutely won't work from here on.

After changing those lines to specify `size=shape`, `pymc3.tests.test_sampling.TestSample.test_sample_init` passes.

Also, these commits need to be squashed (e.g. all the RNG changes in one commit and the JAX ones in another).

2020-12-28 06:01 UTC, kyleabeauchamp commented
It seems like there are still pickle failures in the CI/CD logs, even after we bumped to theano 1.0.14.  E.g.,

```
>       dump = pickle.dumps(three_var_aevb_approx)
E       TypeError: cannot pickle 'module' object
```

2020-12-29 09:05 UTC, twiecki commented
I wonder if the problem is now in the VI module? Is there a way to see which "module"?

2020-12-29 09:18 UTC, brandonwillard commented
Multiple errors are due to the variational tests not having consistent `float[32|64]` types, and at least one other appears to be caused by a numerical error falling outside of a fixed range.  

The former can likely be fixed by correctly setting the test input types, and the latter may be due to a new RNG seeding caused by the change to `RandomStream`.

2020-12-31 01:36 UTC, brandonwillard commented
I've reorganized the commits and made some minor updates to the variational tests, so you'll need to rebase locally.

Once https://github.com/pymc-devs/Theano-PyMC/pull/252 goes through, most of the test failures should be fixed, but I think there's still one remaining.

2020-12-31 03:28 UTC, brandonwillard commented
It looks like there are some unexpected `NullType` gradients in `pymc3.tests.test_variational_inference.test_fit_oo` under the `SVGD-mini` parameter values.   This problem isn't shared by `MRG_RandomStream`, so I've changed `RandomStream` back to `MRG_RandomStream`.

The reason `MRG_RandomStream` isn't producing `NullType`s in this case might be due to how it represents `uniform(a, b)`.  Instead of representing `uniform(a, b)` as a single `Op`, `MRG_RandomStream` constructs a graph of `uniform(a, b)` via `uniform(0, 1) * (b - a) + a`, where `uniform(0, 1)` is the underlying RNG `Op`.

2020-12-31 08:35 UTC, twiecki approved these changes

2020-12-31 08:37 UTC, merged

2020-12-31 08:37 UTC, twiecki commented
Thanks @kyleabeauchamp and @brandonwillard, really glad to have PyMC3 work again with recent Theano.