Implement logcdf method for discrete distributions
pymc-devs/pymc pull request #4387
Opened 2020-12-27 16:38 UTC by ricardoV94

This PR adds `logcdf` methdos to all univariate discrete distributions. Formulas were based in either scipy or wikipedia entries. For some distributions, I could not find specialized formulas and had to rely on summing up all the logps in `tt.arange(0, value+1)`.

Closes #4331

Unittests:
1. Using `check_logcdf` in all distributions with scipy counterpart.
2. Added a new type of unit test `check_selfconsistency_discrete_logcdf`, which tests that the logcdf is equivalent to adding all the logps starting from zero. This provides coverage to the distributions that are not in scipy (not covered by 1.). I added it to all distributions, but maybe this is too redundant for those that are covered by 1. 

Some remaining issues / questions:
1. Should all `bound` calls in CDF methdos be replaced by `tt.switch`? Most `logcdf` methods for continous distributions seem to use `tt.switch`, except for the `Gamma` and `InverseGamma` distributions. I used `bound` whenever there were at least two conditions that needed checking leading no `-np.inf`, otherwise went with `tt.switch`. I am also not completely sure if this interferes with the recent #4377 PR.
2. Several `logcdf` methods do not work with multiple values (or even with an array containing a single value such as `np.array([1])`). In these cases, I excluded information in the docstrings about the possibility of computing the `logcdf` for multiple values, but this seems like a suboptimal solution. We should either fix it or raise a ValueError to explain the limitation to the user, as this seems to go against the expected behavior in most distributions. This occurs for two reasons:
   1. Computing logcdf by summing over the individual logps with `logsumexp(tt.arange(0, value+1), keepdims=False)` for the `BetaBinomial` and `HyperGeometric`. Any alternatives?
   2. Using the `incomplete_beta` function in the `Binomial` and `NegativeBinomial` (and `ZeroInflated` counterparts). This is also an issue in the current implementation of the `Beta` and `StudentT` distributions (see #4342). In addition, the unit tests for these functions seem to be very slow compared to those of other distributions. Is the `incomplete_beta` particularly slow?
3. Slightly different, the `logcdf` method of the `Poisson` distribution (and its `ZeroInflated` counterpart) fails with a C-assertion (exiting the python process altogether) when asked to evaluate multiple invalid values. This is also a problem in the `InverseGamma` distribution (see #4340). It will be solved once this Theano issue is fixed (see https://github.com/pymc-devs/Theano-PyMC/issues/224)
4. Unittests: `check_logcdf` tests only for values in the output domain, ignoring the edge values, but we might want to test also for values at the edges as well as below or beyond the domain (which can be evaluated to either -np.inf or 0). For example `pm.Bernoulli(p=.1).logcdf([-1, 2]) -> [-np.inf, 0]`. Should we use more comprehensive extra-domain checks?

Other changes not directly related to this PR:
1. Added a missing `pymc3_matches_scipy` test to the `BetaBinomial`. Was there a reason why this was missing? 
2. Changed the order of the `logp` and `random` methods in the `DiscreteWeibull` distribution to be in line with the rest of the library.
3. Removed unused local variables in the init methods of `DiscreteWeibull` and `ZeroInflatedPoisson` distributions.

2020-12-29 13:16 UTC, ricardoV94 commented
I am sorry for all the changes after opening the PR. I think it is now ready for review.

2020-12-29 19:57 UTC, AlexAndorra requested changes
This is great, thanks @ricardoV94 !
This is a pretty big PR, so a second review by another core dev would be beneficial.

I agree that the `logcdf` methods that do not work with multiple values should raise a `ValueError` to explain the limitation to the user. Related to this, I added some comments to add the mutiple values' types (numpy array or theano tensor) to the docstrings

2020-12-29 19:57 UTC, AlexAndorra commented on pymc3/distributions/discrete.py
> +        value: numeric
Should probably add the types for multiple values then. Something like the following?
```suggestion
        value: numeric or np.ndarray or theano.tensor
```

2020-12-29 19:57 UTC, AlexAndorra commented on pymc3/distributions/discrete.py
> +        value: numeric
```suggestion
        value: numeric or np.ndarray or theano.tensor
```

2020-12-29 19:57 UTC, AlexAndorra commented on pymc3/distributions/discrete.py
> +        value: numeric
```suggestion
        value: numeric or np.ndarray or theano.tensor
```

2020-12-29 19:57 UTC, AlexAndorra commented on pymc3/distributions/discrete.py
> +        value: numeric
```suggestion
        value: numeric or np.ndarray or theano.tensor
```

2020-12-29 19:57 UTC, AlexAndorra commented on pymc3/distributions/discrete.py
> +        value: numeric
```suggestion
        value: numeric or np.ndarray or theano.tensor
```

2020-12-29 19:57 UTC, AlexAndorra commented on pymc3/distributions/discrete.py
> +        value: numeric
```suggestion
        value: numeric or np.ndarray or theano.tensor
```

2020-12-29 19:57 UTC, AlexAndorra commented on pymc3/distributions/discrete.py
> +        value: numeric
```suggestion
        value: numeric or np.ndarray or theano.tensor
```

2020-12-29 22:19 UTC, ricardoV94 commented
Thanks for the review @AlexAndorra. I agree about the ValueError, although I have to check how to check that with Theano variables.

I was hoping someone would suggest a fix for those that use `tt.arange`. Scipy actually does a loop to return results for multiple values.

About the type hints in the docstring. What if we do a separate PR just for that, so that all logcdfs (discrete and continuous) are homogeneous? Right now, none of the other docstrings have it and they should as well.

2020-12-30 09:14 UTC, twiecki commented on pymc3/distributions/discrete.py
> +        Returns
Needs a new-line.

2020-12-30 09:14 UTC, twiecki commented on pymc3/distributions/discrete.py
> +        Parameters
Needs a new-line.

2020-12-30 09:14 UTC, twiecki commented on pymc3/distributions/discrete.py
> +        Parameters
Above Parameters.

2020-12-30 09:17 UTC, twiecki requested changes
A lot of the doc-strings miss new-lines before Parameters and Returns, otherwise this looks great to me!

2020-12-30 09:20 UTC, ricardoV94 commented
> A lot of the doc-strings miss new-lines before Parameters and Returns, otherwise this looks great to me!

Thanks for reviewing it. I will fix those.

Unrelated to that, does anyone know a good way to check that `value` is not a scalar in order to raise an informative ValueError in those methods that fail with arrays/tensors?

2020-12-30 09:29 UTC, twiecki commented
You can try whether `np.isscalar` works on numpy and theano arrays.

2020-12-31 10:37 UTC, ricardoV94 commented
New commit fixes missing newlines in docstrings and raises informative `TypeError` in logcdf methods that only accept scalars. 

I would address @AlexAndorra suggestion of including more informative docstring type hints, as well as expanding `check_logcdf` unittest to make sure that logcdf methods that fail with nonscalar values raise a `TypeError warning` in #4393. The reason for this is that the logcdf methods of some continuous distributions also need to be changed and I think it would be easier to keep track / review those in that separate PR. Do you agree?

2020-12-31 11:22 UTC, twiecki approved these changes

2020-12-31 11:49 UTC, merged

2020-12-31 11:50 UTC, twiecki commented
This is a great contribution, thanks @ricardoV94!