Update legibility of formula to proper Latex Format
pymc-devs/pymc pull request #4390
Opened 2020-12-28 11:11 UTC by CloudChaoszero

# Description

* Update Normal Distribution's PDF formula in the [Developer Guide](https://docs.pymc.io/developer_guide.html#reflection) section to proper latex format
* Add wiki hyperlink to PDF definition

Note: Added mid-step just to clarify why the PDF is resulted, as such.

Closes #4384

## Output

<img width="1174" alt="Example" src="https://user-images.githubusercontent.com/19514362/103210181-cff4ab00-48b9-11eb-8349-d4e27611ceae.png">

2020-12-28 12:08 UTC, MarcoGorelli requested changes
Thanks @CloudChaoszero 

Instead of writing `where\mu=0`, would it work to use the vertical "evaluated at" line (https://tex.stackexchange.com/questions/40160/math-symbol-question-vertical-bar-for-evaluated-at)?

Finally, I think the `*` sign, and the brackets around `2*\pi` could be removed

2020-12-29 03:01 UTC, CloudChaoszero commented
@MarcoGorelli  Sounds great. Made the update, seen below 

<img width="1232" alt="Example 2" src="https://user-images.githubusercontent.com/19514362/103255661-03c5e400-493f-11eb-810f-0048e578a111.png">

2020-12-29 08:59 UTC, MarcoGorelli commented
Thanks, looks good, but I think you'll want the vertical "evaluated at" line after the third operand, not after the fourth one

Also, could you address

> I think the * sign, and the brackets around 2*\pi could be removed

Finally, there's a linting error due to trailing whitespace, could you resolve that please? See the [style guide](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Python-Code-Style) for how to run the checks, and feel free to ask if it's unclear

2020-12-29 09:24 UTC, CloudChaoszero commented
@MarcoGorelli, Ah, thanks for the tip--found and deleted the whitespace. 

Moreover, I resolved the following & 'evaluated at' piece.
> I think the * sign, and the brackets around 2*\pi could be removed

2020-12-31 18:50 UTC, merged

2020-12-31 18:50 UTC, twiecki commented
Thanks @CloudChaoszero!