Cut new release 3.11.0
pymc-devs/pymc pull request #4424
Opened 2021-01-19 12:34 UTC by Spaak

As per the checklist: https://github.com/pymc-devs/pymc3/wiki/Release-Checklist .

2021-01-19 12:45 UTC, OriolAbril approved these changes

2021-01-19 12:54 UTC, michaelosthege requested changes
Just some things still missing from the readme

2021-01-19 12:54 UTC, michaelosthege commented on RELEASE-NOTES.md
> +- We now depend on `Theano-PyMC` version `1.1.0` or greater (see [#4405](https://github.com/pymc-devs/pymc3/pull/4405)).
To be precise, this release depends on exactly `Theano-PyMC v1.1.0`.

2021-01-19 12:54 UTC, michaelosthege commented on RELEASE-NOTES.md
> +- We now depend on `Theano-PyMC` version `1.1.0` or greater (see [#4405](https://github.com/pymc-devs/pymc3/pull/4405)).
Let's also add a line (above or in "Breaking changes") about the most important changes in `Theano-PyMC`:
```
Major refactorings were done in Theano-PyMC 1.1.0, if you implement custom `Op`s or interact with Theano in any way yourself, make sure to read the [Theano-PyMC 1.1.0 release notes](https://github.com/pymc-devs/Theano-PyMC/releases/tag/rel-1.1.0).
```

2021-01-19 14:26 UTC, twiecki approved these changes

2021-01-19 16:06 UTC, aloctavodia commented
After merging #4310 we should add something like 

BART: Add a new `predict` method to compute out of sample predictions evaluated at new X values (see [#4310](https://github.com/pymc-devs/pymc3/pull/4310)).

2021-01-19 16:12 UTC, Spaak commented
@aloctavodia ideally add the changes to the release notes inside #4310 before merging.

2021-01-19 16:14 UTC, michaelosthege commented
> @aloctavodia ideally add the changes to the release notes inside #4310 before merging.

I just merged already. Editing the release notes in #4310 would have created a git conflict and also would have taken another 45 minutes of CI...

2021-01-20 19:49 UTC, twiecki commented
Alright! All other issues are closed so we can merge this and release.

2021-01-21 07:41 UTC, Spaak commented
Yep! On it right now.

2021-01-21 08:17 UTC, michaelosthege approved these changes
LGTM 🎉

2021-01-21 08:20 UTC, merged

2021-01-21 09:41 UTC, twiecki commented
Woohoo!