Fast doc build
pymc-devs/pymc pull request #4477
Opened 2021-02-15 13:48 UTC by Pyrsos

Sorry, made a mess on this with the branches. Here are the latest changes for building the docs fast issue #4435
Again apologies for the mess...

Depending on what your PR does, here are a few things you might want to address in the description:
+ [ ] what are the (breaking) changes that this PR makes?
+ [ ] important background, or details about the implementation
+ [ ] are the changes—especially new features—covered by tests and docstrings?
+ [ ] [linting/style checks have been run](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Python-Code-Style)
+ [ ] [consider adding/updating relevant example notebooks](https://github.com/pymc-devs/pymc-examples)
+ [ ] right before it's ready to merge, mention the PR in the RELEASE-NOTES.md

2021-02-15 18:13 UTC, OriolAbril reviewed
Looks good, I would name the file `fast_build_docs.sh` though, as this one does not deploy them to github pages (and should not)

2021-02-16 13:32 UTC, MarcoGorelli requested changes
Thanks @Pyrsos , much faster like this!

Have just left one small comment, other than that it looks good to me

2021-02-16 13:32 UTC, MarcoGorelli commented on fast_build_docs.sh
> +#!/bin/sh
This didn't work for me, I had to change it to:
```suggestion
#!/bin/bash
```

2021-02-16 13:37 UTC, MarcoGorelli commented
As an aside, maybe there should be another script `build_docs.sh` which:
- fetches the latest changes from the `main` branch in `pymc-examples` (`git submodule update --remote`)
- builds the full docs without deploying them

Even better if they could be Python scripts instead of bash ones, so that any contributor on any OS can easily build the docs with just one script - but these can be separate

----

Last piece of advice here would be to make PRs from new branches rather than from master

2021-02-19 13:44 UTC, Pyrsos commented
Sorry for the delay @MarcoGorelli, I have now made the suggested changes. I'd be happy to work on a separate PR for your suggestions to change from bash scripts to Python scripts. Should I open an issue for this?

2021-02-19 14:07 UTC, MarcoGorelli approved these changes
cool, thanks!

and yes, I think opening an issue would be good so it doesn't get forgotten

2021-02-19 14:12 UTC, OriolAbril approved these changes

2021-02-21 22:37 UTC, Pyrsos commented
OK, I have opened another issue here #4483. Is there anything else I need to do with this one or can it be merged? I do not think I have write access to the repository to do the merge.

2021-02-22 23:18 UTC, merged

2021-02-22 23:18 UTC, OriolAbril commented
This is all for now, the other tasks have issue remainders and can be done in follow up PRs. Thanks for the PR @Pyrsos !