Fix exponential and gamma logp / random link
pymc-devs/pymc pull request #4576
Opened 2021-03-27 10:53 UTC by ricardoV94

After merging #4548, the `Exponential` and `Gamma` distributions still have a mismatch between the logp and random parametrizations. 

I still think it is more straightforward to keep relying on the tests in `test_distributions.py` while we refactor the distributions into V4 as it easily identifies this type of issues. There is already an open issue to refactor these tests #4554, so it will not be forgotten.

For the discussion into the Exponential and Gamma changes see my previous comments:
1. Exponential: https://github.com/pymc-devs/pymc3/pull/4548#discussion_r596715512
2. Gamma: https://github.com/pymc-devs/pymc3/pull/4548#issuecomment-801750855

There seems to be a problem with the Categorical (tested locally), but perhaps it was addressed by https://github.com/pymc-devs/aesara/pull/351?

2021-03-27 16:21 UTC, brandonwillard requested changes
We do not need to create that new `RandomVariable` or add a new optional parameterization at this time.

2021-03-27 17:41 UTC, ricardoV94 commented
What do you suggest instead?

2021-03-27 18:39 UTC, brandonwillard commented
> What do you suggest instead? Shall we leave the distributions not matching parameters on the logp and random sides?

We only need to keep the `Distribution` interface, so, inside `Exponential.dist`, can `at.inv` the parameter and update the corresponding `logp` and `logcdf` functions.  The latter two functions are not called directly, so they only need to correspond to the `RandomVariable` parameterizations.

2021-03-29 08:01 UTC, ricardoV94 commented
I removed the explicit new parametrization of the `exponential` and forced the `gamma` to work with the parameter inversion on the aesara side. The last one still feels weird, but if that's how we want to keep it, so be it.

2021-03-29 18:42 UTC, brandonwillard commented
I rebased this branch onto the update `v4`.

2021-03-29 18:52 UTC, ricardoV94 commented
Thanks!

2021-03-30 07:22 UTC, ricardoV94 commented
I changed the exponential `equal` assertion to `almost_equal` as it was failing on `float32`. The tests should pass now.

2021-03-30 07:50 UTC, ricardoV94 commented
Unrelated to this PR this test failed:
`test_sampling.py::test_exec_nuts_init`

2021-04-03 21:49 UTC, brandonwillard approved these changes

2021-04-04 06:38 UTC, merged