Update version string and add warning on import.
pymc-devs/pymc pull request #4726
Opened 2021-05-27 09:27 UTC by twiecki

2021-05-27 09:53 UTC, ricardoV94 commented on pymc3/__init__.py
> +    "You are running the development version of PyMC3 which currently still lacks key features."
Perhaps add something along the lines of:

> The latest stable release is version `3.11.2`.

2021-05-27 15:07 UTC, brandonwillard commented
Side note: have we considered setting up `versioneer`?

2021-05-27 15:08 UTC, brandonwillard approved these changes
These changes look fine, but I don't know what the failures are about, yet.

2021-05-27 15:18 UTC, brandonwillard requested changes
Ah, looks like [the error](https://github.com/pymc-devs/pymc3/pull/4726/checks?check_run_id=2683532131#step:7:311) is due to the version string.

2021-06-05 08:49 UTC, twiecki commented on pymc3/__init__.py
> +__version__ = "4.0.dev0"
```suggestion
__version__ = "4.0"
```

2021-06-05 08:57 UTC, merged