Bring back `SMC` and allow `prior_predictive_sampling` to return transformed values
pymc-devs/pymc pull request #4769
Opened 2021-06-14 15:17 UTC by ricardoV94

SMC was broken after the refactoring because it starts with a `prior_predictive_sampling` call to set up the particles positions, expecting it to return also transformed values. I extended `prior_predictive` to return transformed values if (and only if) transformed variables are explicitly passed in the optional `var_names` argument. For reference, in `v3` transformed variables were returned by default. If anyone has a strong opinion about the old default let me know!

Tests were added for this as well as for the now stale issue #4490 

Depending on what your PR does, here are a few things you might want to address in the description:
+ [x] what are the (breaking) changes that this PR makes?
+ [x] important background, or details about the implementation
+ [x] are the changes—especially new features—covered by tests and docstrings?
+ [x] [linting/style checks have been run](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Python-Code-Style)
+ [x] [consider adding/updating relevant example notebooks](https://github.com/pymc-devs/pymc-examples)
+ [ ] right before it's ready to merge, mention the PR in the RELEASE-NOTES.md

2021-06-14 16:50 UTC, junpenglao approved these changes
LGTM

2021-06-15 09:01 UTC, michaelosthege approved these changes

2021-06-15 09:04 UTC, michaelosthege requested changes
These failing tests look systematic. Some kind of dytpe problem..

2021-06-15 13:23 UTC, ricardoV94 commented
> These failing tests look systematic. Some kind of dytpe problem..

Definitely. One of the SMC tests is failing in float32 when there is a discrete variable. It happens in the `join_nonshared_inputs` which concatenates all the raveled variables, leading to an upcast to `float64` when there are both discrete and continuous variables (since discretes are `int64`).

https://github.com/pymc-devs/pymc3/blob/f7d460212c0539e6c7a7ae394a3f2de6416068c7/pymc3/aesaraf.py#L604-L608

The problem then is that the input can no longer be of type `float32`.

This should be a problem in other areas of the codebase that make use of this function. I've seen it in `metropolis.py`, `mlda.py` and `pgbart.py`.

2021-06-15 13:36 UTC, ricardoV94 commented
Also, more in general, within SMC we are treating discrete variables as continuous (e.g., in the proposal). Are we comfortable with this @aloctavodia?

2021-06-16 07:52 UTC, ricardoV94 commented
I temporarily disabled `trust_input` to pass the tests. I tried a bunch of things (mostly with `clone_replace` + `casting`) to allow the `prior_logp_func` function to accept `float32` inputs  in models with discrete variables, without success.

2021-06-16 15:29 UTC, junpenglao approved these changes

2021-06-16 20:11 UTC, michaelosthege approved these changes

2021-06-16 20:15 UTC, merged

2021-06-17 07:07 UTC, aloctavodia commented
Sorry for being late to the party. Yes I am conformable with treating discrete variables as continuous when proposing new values.

2021-11-08 14:35 UTC, OriolAbril commented
I saw this checking the release notes in:

> pm.sample_prior_predictive no longer returns transformed variable values by default. Pass them by name in var_names if you want to obtain these draws (see 4769).

The converter to InferenceData ignores transformed values by default, so I find the phrasing is a bit misleading and potentially troublesome. We should probably add an argument to the converter to include transformed variables into the inferencedata otherwise we'll need to keep the dict return and the capabilities of the function will depend on the output chosen

2021-11-08 14:40 UTC, ricardoV94 commented
The plan is to revert this, see #https://github.com/pymc-devs/pymc/issues/5076

This is no longer needed, as we can use the model.initial_point to get transformed prior predictive samples when they are needed for our samplers

2021-11-08 14:55 UTC, OriolAbril commented
I think I should probably go over issues and PRs in both pymc and arviz and make a serious cleanup of integration with InferenceData. We still have arguments that were more workarounds than actual arguments/fixes and should be removed as they are generally useless now (i.e. density_dist_obs in to_inferende_data, keep_size in sample_posterior_predictive), the transforms presence is also annoying: https://github.com/arviz-devs/arviz/issues/1509, https://github.com/arviz-devs/arviz/issues/230, and in general we can simplify the converter quite a bit now that it lives in the pymc codebase and should not need complicated logic to work with multiple pymc versions. I think we could also make pointwise log likeihood storage and posterior predictive sampling work with dask (as in my experience it is common that the model/posterior fits in memory but there are many observations and ll and pp do not, and arviz does support working with dask backed arrays, the main limitation right now is creating those dask backed arrays).

Maybe other improvements are also relaatively low hanging fruit?