Fix tuning of Compound step with multiple chains in serial
pymc-devs/pymc pull request #4886
Opened 2021-07-28 08:29 UTC by msibaev

**Thank your for opening a PR!**

Depending on what your PR does, here are a few things you might want to address in the description:
+ [ ] what are the (breaking) changes that this PR makes?
+ [ ] important background, or details about the implementation
+ [ ] are the changes—especially new features—covered by tests and docstrings?
+ [ ] [linting/style checks have been run](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Python-Code-Style)
+ [ ] [consider adding/updating relevant example notebooks](https://github.com/pymc-devs/pymc-examples)
+ [ ] right before it's ready to merge, mention the PR in the RELEASE-NOTES.md

2021-08-05 07:45 UTC, msibaev commented
Some samplers have a `tune` variable and no `reset_tuning` method. That's why [`_iter_sample()`](https://github.com/pymc-devs/pymc3/blob/main/pymc3/sampling.py#L1016-L1018)  cannot rely on calling `reset_tuning()` only.

Note, `DEMetropolis`  only accepts `tune` values in `[None, "scaling", "lambda]"`, but `_iter_sample` sets it to `bool`. As a result, tuning won't be performed during a step, see [here](https://github.com/pymc-devs/pymc3/blob/main/pymc3/step_methods/metropolis.py#L734-L737). This has been fixed in `DEMetropolisZ` by introducing [`tune_type`](https://github.com/pymc-devs/pymc3/blob/main/pymc3/step_methods/metropolis.py#L864-L867) parameter and making `tune` boolean. I'll need to create a separate PR for this.

2021-08-05 08:21 UTC, msibaev commented
Variable `iter_count` is used by `NUTS` to effect [max tree depth during tuning](https://github.com/pymc-devs/pymc3/blob/main/pymc3/step_methods/hmc/nuts.py#L175-L176) and by `base_hmc` in warning messages [here](https://github.com/pymc-devs/pymc3/blob/main/pymc3/step_methods/hmc/base_hmc.py#L163-L168) and [here](https://github.com/pymc-devs/pymc3/blob/main/pymc3/step_methods/hmc/base_hmc.py#L205-L214).

It can be set to 0 in `reset_tuning` as well. Although, it seems what `_iter_sample` needs is a general `step.reset()` method which brings it back to the original configuration. However, for most samplers `reset()` will simply call `reset_tuning()`, except for `NUTS` which would also set `iter_count=0`. It's not worth adding extra layer of complexity for only one step sampler.

2021-08-09 20:32 UTC, michaelosthege commented
Hi @msibaev ,
Sorry about the delay. I just got the chance to read your descriptions and look at the changes. I believe the history was such that in the beginning there was only a boolean tune parameter, but the typing of that interface diffused away over time.
When I implemented `DEMetropolis` the boolean setting was no longer enough, because the sampler had to reset some things when switching in/out the tuning phase. If I remember correctly that's when I introduced the `reset_tuning` method.

At the `_iter_sample` level we can't deal with all the specifics of the different samplers, so yes we should unify that to one interface.

2021-09-13 09:12 UTC, msibaev commented
Hi @michaelosthege

I don't get much time to look at these things nowadays, sorry for the delay. 

Thanks for the context of `rest_tuning()`.  I guess there should be some more standardization across all samplers in that respect, which would allow `_iter_sample()` to be cleaned up a bit more. But, that probably goes beyond the scope of this PR. My main goal was just to fix tuning when multiple chains are running in serial. It's an edge case, but an important one for windows machines where multiprocessing can be buggy.

Is there anything else that you think should be done here?

2021-09-13 17:00 UTC, michaelosthege requested changes
hI @msibaev, thank's for picking it up again.

I think we should go for the long-term solution right away. It seems to me that it could be realized with equally few changes.

Another thing we'll need to is a mention of this PR and the API change with respect to tuning reset in the `RELEASE-NOTES.md`.

2021-09-13 17:00 UTC, michaelosthege commented on pymc3/tests/test_step.py
> +        __, model = simple_2model_continuous()
Typically we use single underscores. Not sure if the pre-commit may complain about it...

2021-09-13 17:00 UTC, michaelosthege commented on pymc3/tests/test_step.py
> +                    assert [[True, True], [False, False], [False, False]] == tune_method
The name of the test implies that this should be about sequential chains. So I guess at least one more chain should be "sampled", after calling `reset_tuning`?

2021-09-13 17:00 UTC, michaelosthege commented on pymc3/step_methods/compound.py
> +
The `reset_tuning` method above already does a very similar thing. I would prefer if we didn't add a `tune` property here, but instead add/implement the `reset_tuning` method on the steppers that currently don't reset their `tune` setting themselves.

With small modifications (see below) the `test_tune_parameter_in_sequential_chain_sampling` test you wrote seems to be well-suited to verify that behavior for the samplers that currently don't reset correctly.

2021-09-13 17:00 UTC, michaelosthege commented on pymc3/sampling.py
> -                step.iter_count = 0
I like this!

2021-11-19 09:37 UTC, michaelosthege commented on pymc3/step_methods/metropolis.py
> +    initial_settings: dict[str, Any]
```suggestion
    initial_settings: Dict[str, Any]
```
To fix the docs build.

2022-01-02 00:48 UTC, michaelosthege commented
Hi @msibaev , I see you're working on this branch again. Cool!
Let us know when it's ready for review

2022-01-03 08:58 UTC, msibaev commented on pymc3/tests/test_step.py
> +        __, model = simple_2model_continuous()
Thanks, I'll use single underscore to be consistent.

2023-03-15 00:07 UTC, ricardoV94 commented
Would be good to ooen an issue for the problem this PR was trying to address, as it's been stale for a while

2023-08-24 11:26 UTC, ricardoV94 commented
Closing this due to lack of activity and the fact it is targeting V3

2023-08-24 11:26 UTC, closed without merging