[Docs Team] Glossary - Dispersion
pymc-devs/pymc pull request #4984
Opened 2021-09-05 16:46 UTC by CloudChaoszero

# Description
* Add "Dispersion"-related definitions in PyMC glossary
* [Optional]: Creating template for adding terms into Glossary

2021-09-06 15:03 UTC, martinacantaro reviewed
The Underdispersion entry links to the Overdispersion wikipedia page.

I don't think it's necessary to write the definitions inside quotation marks. 

For the dispersion definition, I would try to clarify what 'streched' and 'squeezed' mean, as it is a bit ambiguous

2021-09-07 22:11 UTC, OriolAbril reviewed
Many of these definitions (especially also looking at the issue and other PRs) are quite complicated and many talks have been given and book chapters written about them, so I think it is very important to be generous with links and references.

I have added a suggestion to link to "dispersion" from the definition of overdispersion (same should be done for underdispersion). I think many definitions will need to refer to other terms.

It might also be a good idea to add some references or seealso links. We can discuss that during the meeting, but as this is mostly oriented at newcomers, we could recommend a section of 1-2 books to dive deeper into that term/area which would link the resources repo with this one much more

2021-09-07 22:11 UTC, OriolAbril commented on docs/source/glossary.md
> +  "In statistics, overdispersion is the presence of greater variability (statistical dispersion) in a data set than would be expected based on a given statistical model."
```suggestion
  "In statistics, overdispersion is the presence of greater {term}`variability <dispersion>` in a data set than would be expected based on a given statistical model."
```

2021-09-30 02:35 UTC, martinacantaro commented
Task linked: [CU-5t5y0p Glossary](https://app.clickup.com/t/5t5y0p)

2021-10-03 06:40 UTC, CloudChaoszero commented
Sounds great @martinacantaro. I also added Oriol's recommendation

2021-10-05 03:32 UTC, martinacantaro requested changes
Looking good! Solved some conflicts, I'm fine with merging it now and creating some issues to resolve later if there's anything we want to improve upon @OriolAbril . I'd suggest moving links out of the definition titles in the future.

(Edited this issue so although this is categorized "request for changes" type of review, I'm not requesting any changes).

2021-10-05 03:32 UTC, martinacantaro commented on docs/source/glossary.md
>  [Term with external reference](https://www.youtube.com/watch?v=6dc7JgR8eI0)
Remove this section

2021-10-06 12:27 UTC, OriolAbril commented on docs/source/glossary.md
> +
There should be no space between the directive start and it's arguments (i.e. the `:sorted:` thing)

2021-10-06 12:27 UTC, OriolAbril commented on docs/source/glossary.md
> -Dispatching
Functional programming and dispatching are actual glossary terms, not examples.

2021-10-07 15:54 UTC, martinacantaro approved these changes

2021-10-07 16:02 UTC, martinacantaro commented
/pre-commit-run

2021-10-11 07:17 UTC, CloudChaoszero commented
@martinacantaro are there any additional edits for this? I saw you made some great commits, appreciate it!

2021-10-14 00:40 UTC, merged