Deprecated
pymc-devs/pymc pull request #5040
Opened 2021-10-04 22:31 UTC by mjhajharia

this pr is made to branch out efforts in #5008 which will be a draft for figuring out the auto formatting sphinx with respect to deprecated parameters. this PR does the following:
- deprecator that deprecated functions or classes (lets you choose to emit or not emit warnings) 
- tests for deprecator
- adds deprecated in docstring for methods, functions and classes
- additionally you can deprecate arguments as well. to be able to document argument deprecation im doing #5008 

things to do:

- [ ] add a docstring for what the parameters in the deprecator function do
- [ ] replace existing deprecated functions or classes with this decorator
- [ ] make a table of all the deprecated functions in documentation

2021-10-08 14:09 UTC, michaelosthege requested changes
@mjhajharia you'll definitely need to run `pre-commit run --all` here. It will make a ton of formatting changes.

This PR doesn't need to migrate a ton of existing deprecation warnings (in fact it's probably easier to cherry-pick it to `v3` if it doesn't).
But maybe you'll want to take _any_ existing deprecation warning and replace it with the decorator so you can check the docs build if the docstring stuff worked.

2021-10-08 14:09 UTC, michaelosthege commented on pymc/tests/test_util.py
> +# tests for deprecator
Instead of a comment, better group these tests in a `TestDeprecatorDecorator` class

2021-10-08 14:09 UTC, michaelosthege commented on pymc/util.py
> +    PyMC deprecation helper. This decorator emits deprecated warnings.
Please add docstrings about the parameters. If applicable you can also link the GitHub/Stackoverflow pages from where you got larger code snippets right in the docstring.

2021-10-08 14:09 UTC, michaelosthege commented on pymc/util.py
> +            #if deprecated arguments are given, docstring is not modified
Indentation. _Maybe_ black will correct it, but if not please indent manually

2021-10-14 15:47 UTC, michaelosthege reviewed
I didn't look at the generated docs, but maybe these comments already help

2021-10-14 15:47 UTC, michaelosthege commented on pymc/tests/test_util.py
> +    def test_warning_msg():
On this and the other test methods you need to include a `self` in the method arguments.
I guess that's also why according to codecov these lines weren't covered.

2021-10-14 15:47 UTC, michaelosthege commented on pymc/util.py
> +        PyMC version in which the method or class was deprecated.
IIRC one of these 3rd party libraries takes two version arguments. It is something like
* `deprecated_in : str` Library version when the deprecation was added.
* `removed_in : str` Version number when it stops working.

When the class/function/method/kwarg is then used with a library version that is >= the `removed_in`, the decorator could automatically raise an exception.
This way we can't bump the version without following through on deprecations, or at least modifying the upper bound.

However, if we do this, we need to consider the case of working on the `main` branch where we typically are already at a version > than the latest release. But we could just append a `-dev` there and remove it before a release.

2021-10-14 19:33 UTC, mjhajharia commented
closing in favour of https://github.com/tantale/deprecated/pull/51

2021-10-14 19:33 UTC, closed without merging