Fixed Interpolated Distribution's interval transform initialization
pymc-devs/pymc pull request #5067
Opened 2021-10-10 04:40 UTC by kc611

Linked Issue: https://github.com/pymc-devs/pymc/issues/5048

2021-10-10 05:37 UTC, ricardoV94 requested changes
Looks good, but we should add a regression test

2021-11-09 09:49 UTC, ricardoV94 requested changes

2021-11-09 09:49 UTC, ricardoV94 commented on pymc/tests/test_distributions.py
> +            x = pm.Interpolated("interpolated", x_points, pdf_points)
We should assert something, even though this was failing before the PR by itself. Perhaps eval the logp outside of the range and check it's not -inf?

2021-11-25 13:04 UTC, ricardoV94 approved these changes

2021-11-25 13:05 UTC, ricardoV94 commented
@kc611 I updated the PR. Let me know if you see any problems

2021-11-25 14:18 UTC, kc611 reviewed
Looks Good. Back then I was confused as of what tests to add. This looks pretty reasonable.

2021-11-25 16:38 UTC, merged