Added check that nu must be a scalar in MvStudentTRV
pymc-devs/pymc pull request #5241
Opened 2021-12-05 09:02 UTC by sagartomar

This should fix issue #5214

2021-12-05 11:15 UTC, ricardoV94 commented on pymc/distributions/multivariate.py
> +        nu = at.as_tensor_variable(floatX(nu))
```suggestion
        nu = at.as_tensor_variable(nu)
```
I think we don't need the `floatX` here, that is something that belongs to PyMC distributions.

2021-12-05 11:18 UTC, ricardoV94 requested changes
Looks great. I left a suggestion below, and we should add a test that covers this branch.

Perhaps in `test_distributions_random` you can add something along the lines of the following one:

https://github.com/pymc-devs/pymc/blob/95bd5e59f940cfbd4076dd21d93b0e2aec270add/pymc/tests/test_distributions_random.py#L1622-L1632

2021-12-11 23:13 UTC, michaelosthege approved these changes
Looks good!
I like the `re.escape(msg)` it always takes me ages to find the right escape syntax..

2021-12-12 06:54 UTC, ricardoV94 approved these changes
Looks great

2021-12-12 06:56 UTC, merged