Updates to GLM and model comparison notebooks
pymc-devs/pymc pull request #5269
Opened 2021-12-17 16:45 UTC by fonnesbeck

This updates the GLM and model comparison notebooks to use v4.0 beta.

2021-12-18 14:51 UTC, tomicapretto commented
<p>You're right. Bambi still relies on v3 and it uses Theano.</p><p> </p><p>The development version is not able to run on v4, but I think it is something we could implement without much difficulty. There's only one thing that may be problematic and it is related to the <code>LKJCholeskyCov</code>   distribution. I don't know if it is already working on v4 already.</p><p> </p><p>I plan to make a new release in the first half of January. We could work on porting Bambi development version to v4 after that.&nbsp;</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-18 16:00 UTC, fonnesbeck commented
<p>I had theano-pymc installed in the env, which caused this. Goes away when I remove it.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-19 19:21 UTC, OriolAbril requested changes
marking with request changes to make sure we update the text to reflect what the code does and the current situation.

I also think it should not use first person "I" anymore as it's no longer a blogpost but a collaborative page in the docs.

2021-12-20 17:47 UTC, fonnesbeck commented
Draft of getting started notebook added. Will finish it up in the next few hours.

2021-12-20 18:10 UTC, OriolAbril commented
could we rename that notebook to `intro_for_ppl_practitioners` or something along these lines? 

I think it is a great notebook _for this audience_ (which imo is what it was aiming for, after all this is based on the paper whose audience is clearly ppl practitioners who keep up with the literature), but it's not really a getting started notebook. New users writing their first bayesian model with a ppl should not need arbitrary logprob terms, distributions nor using aesara explicitly and therefore none of that should be mentioned if writing a [tutorial](https://diataxis.fr/tutorials/). I think having a "pressing void" on a getting started for pymc newcomers might make it a bit more of a priority. 

On a related note, maybe we could base the getting started notebook on @AustinRochford webinar for the upcoming pymc-data umbrella series which could then be notebook with a talk.

2021-12-20 18:15 UTC, twiecki commented
Completely agree @OriolAbril. I think we want a "Getting started if you know Bayesian modeling" and one if you don't.

2021-12-20 19:17 UTC, fonnesbeck commented
I'm all for that, but we should probably not let that be a blocker for getting out of beta. 

How about we rename this one `pymc_overview.ipynb` which is a more accurate description?

2021-12-21 08:42 UTC, OriolAbril commented
> I'm all for that, but we should probably not let that be a blocker for getting out of beta.

agreed, the blockers should be having everything in the api following the template in #5266 and addressing the TODOs currently visible in the website. @martinacantaro knows better and we'll try to organize when she is back after new year.

> How about we rename this one pymc_overview.ipynb which is a more accurate description? 

that is perfect

> We can then add the intro for non-Bayesians notebook later. Its not clear whether that would belong here or with pymc-examples.

It should definitely be here I think. The idea was to have a handful of notebooks included in the versioned docs (and therefore always executed with the version of the docs, I'll try to set up CI for this) covering the core functionalities of pymc.

2021-12-21 08:46 UTC, twiecki commented
<p>I'd either update the cell or just manually type out that this was on version 4.0.0b1. We update these NB so infrequently that we can expect these warnings to be here for a long time.</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-21 08:50 UTC, OriolAbril commented
<p>going forward, this might still be true for pymc-examples but won't and can't be the case with these notebooks. Moving them back here and doing so with only a handful is to make them part of the versioned docs. Will try to set up CI to autoexecute and everything, but these notebooks need to always be executed with the current version of the documentation. If that can't be for some reason (i.e. too long to run on ci) then they have to be moved back to pymc-examples.</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-21 16:29 UTC, fonnesbeck commented
<p>Removed</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-21 16:30 UTC, fonnesbeck commented
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-21 16:30 UTC, fonnesbeck commented
<p>I've revised all this now.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-21 16:30 UTC, fonnesbeck commented
<p>Fixed.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-21 16:30 UTC, fonnesbeck commented
<p>Fixed.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-21 16:38 UTC, fonnesbeck commented
<p>Should be fixed now. bambi installs theano-pymc as a dependency, which is not ideal, but I assume that goes away in the near future when it is updated to PyMC4/Aesara.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-21 16:41 UTC, fonnesbeck commented
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-21 16:41 UTC, fonnesbeck commented
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-21 16:45 UTC, fonnesbeck commented
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-21 16:47 UTC, fonnesbeck commented
<p>Fixed </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-21 16:47 UTC, fonnesbeck commented
<p>Removed the initial value altogether</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-21 20:06 UTC, OriolAbril reviewed
these links won't work yet I think because the name change will have an effect on latest only, not stable. but once v4 is released this is where the notebook will be (and stay)

2021-12-21 20:06 UTC, OriolAbril commented on README.rst
> +Check out the `PyMC overview <https://docs.pymc.io/en/stable/pymc-examples/examples/pymc_overview.html>`__,  or
```suggestion
Check out the `PyMC overview <https://docs.pymc.io/en/stable/learn/examples/pymc_overview.html>`__,  or
```

2021-12-21 20:06 UTC, OriolAbril commented on README.rst
> +-  The `PyMC tutorial <https://docs.pymc.io/en/stable/pymc-examples/examples/pymc_overview.html>`__
```suggestion
-  The `PyMC tutorial <https://docs.pymc.io/en/stable/learn/examples/pymc_overview.html>`__
```

2021-12-22 12:42 UTC, twiecki commented
<p>These do not look that great, or is that the point? Why not pick non-fat-tailed priors?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-22 12:43 UTC, twiecki commented
<p>Still see it: switchpoint = pm.DiscreteUniform(</p><p>&nbsp;&nbsp;&nbsp;&nbsp;"switchpoint", lower=years.min(), upper=years.max(), testval=1900</p><p>&nbsp;&nbsp;)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-22 12:59 UTC, twiecki commented
I think these could be great getting started guides already. one for if you do not know Bayesian modeling, one if you do.

2021-12-24 21:48 UTC, fonnesbeck commented
<p>Its a horseshoe prior. If we chose normal priors we would not be doing sparse regression.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-24 21:49 UTC, fonnesbeck commented
<p>I can remove it.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-24 21:50 UTC, fonnesbeck commented
<p>I think its important to show that other samplers can be used. There's nothing wrong with the slice sampler. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-24 21:50 UTC, fonnesbeck commented
<p>Good idea.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-27 20:13 UTC, fonnesbeck commented
<p>No, that strips away all the x-axes labels except for the bottom one.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-27 20:37 UTC, fonnesbeck commented
<p>The plot looks better but it does a poor job with the labels (see newly-pushed version)</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-27 20:57 UTC, fonnesbeck commented
<p>I can't seem to get any of these working here. I will leave them as markdown for now.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-27 22:20 UTC, OriolAbril commented
<p>Oh yeah, it looks like ArviZ sets the grid and ticklables to match the centers of the bins. Changing the order should look better but we should probably add a way to turn this off in ArviZ and have regular grid and ticklabels not tied to any histogram (which doesn't make much sense when comparing)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-27 22:21 UTC, OriolAbril commented
<p>wasn't sure it'd work, let's forget about this</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-28 15:20 UTC, fonnesbeck commented
<p>The problem here is that I want the text to say "platform-specific installation guides" and not simply "installation"</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-28 15:23 UTC, fonnesbeck commented
<p>Similar to above, I don't want the text to say "api" I want it to say "API documentation".</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-28 17:23 UTC, OriolAbril commented
There are some examples of custom text in https://sphinx-primer.readthedocs.io/en/latest/core/roles.html

2021-12-31 01:25 UTC, fonnesbeck commented
<p>I've updated these passages</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-31 01:25 UTC, fonnesbeck commented
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-31 01:26 UTC, fonnesbeck commented
<p>done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-31 01:38 UTC, fonnesbeck commented
<p>Unfortunately swapping the order creates xticklabels that overlap to the point of unreadability. I have left it as is for the time being.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc/pull/5269/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-31 01:40 UTC, fonnesbeck commented
I think I've addressed all of the comments as best as possible. Let me know if there is anything else that needs attention.

2021-12-31 12:54 UTC, OriolAbril commented
```
{ref}`API documentation <api>`
{ref}`platform-specific installation guides <installation>`
```

Will point to the right place and show the custom text. There shouldn't be links hardcoded to v3 docs unless they aim to always point there.

2022-01-07 02:05 UTC, OriolAbril approved these changes

2022-01-07 16:15 UTC, merged