Add softmax math
pymc-devs/pymc pull request #5279
Opened 2021-12-22 10:12 UTC by ricardoV94

This PR adds softmax and log_softmax wrappers to the new Aesara Ops which accept the axis argument. The wrappers are there just to suppress the deprecation warnings issue on the Aesara side.

2021-12-22 21:58 UTC, twiecki approved these changes

2021-12-23 07:19 UTC, ricardoV94 commented
Some scary looking errors on windows: https://github.com/pymc-devs/pymc/runs/4605536352?check_suite_focus=true#step:7:21

2022-01-07 16:49 UTC, michaelosthege requested changes
This PR is blocked by https://github.com/aesara-devs/aesara/issues/707 and will be delayed until  we can upgrade to an Aesara release that includes a fix.

2022-01-20 15:58 UTC, ricardoV94 commented on pymc/math.py
> +    with warnings.catch_warnings():
I checked locally that this does not screw up UserWarnings elsewhere

2022-01-20 16:00 UTC, michaelosthege approved these changes

2022-01-20 16:14 UTC, twiecki approved these changes

2022-01-20 16:14 UTC, merged