Option to create non-shared `pm.Data`
pymc-devs/pymc pull request #5295
Opened 2021-12-30 16:19 UTC by michaelosthege

Until now `pm.Data` always created a `SharedVariable`, even though most uses of `pm.Data` are not because it's mutable, but because it registers the variable in the model.

With `pm.Data(..., mutable=False/True)`, this PR adds the option to create non-shared data variables (`TensorConstant`) that possibly improve performance (via optimizations available for `TensorConstant`) and can also be used in places where a `SharedVariable` is not supported.

I also refactored `pm.Data` from a class into a function. I'm not 100 % sure why it was a class in the first place, but if I understand it correctly our use of `__new__` actually violates its intended signature, since we're not returning an instance of the correct type(?).

Depending on what your PR does, here are a few things you might want to address in the description:
+ [x] what are the (breaking) changes that this PR makes? The `pm.Data.get_coord` staticmethod was refactored to `pm.data.determine_coords`, but this is just internal API.
+ [x] important background, or details about the implementation. See above.
+ [x] are the changes—especially new features—covered by tests and docstrings? Yes.
+ [x] [linting/style checks have been run](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Python-Code-Style)
+ [consider adding/updating relevant example notebooks](https://github.com/pymc-devs/pymc-examples) 👉 Do we want to add a deprecation warning when `mutable` is not specified? We could also make `mutable=None` by default and warn that the default will change in the future?
+ [ ] right before it's ready to merge, mention the PR in the RELEASE-NOTES.md

2021-12-30 16:26 UTC, michaelosthege commented
@ricardoV94 these changes could help for #4441 - I didn't test it, but with a (float) `pm.ConstantData/TensorConstant` having NaN values one could get at least the dims/coords/InferenceData.constant_data functionality also for imputation.

2021-12-30 19:57 UTC, ricardoV94 commented
> @ricardoV94 these changes could help for #4441 - I didn't test it, but with a (float) `pm.ConstantData/TensorConstant` having NaN values one could get at least the dims/coords/InferenceData.constant_data functionality also for imputation.

Yes it should be possible, just need to consider the TebsorConstant case in there

2022-01-01 09:38 UTC, ricardoV94 approved these changes

2022-01-03 03:02 UTC, twiecki commented
In `pm.set_data()` can we check if it was unmutable and then give an informative error?

Also, should the default really be mutable=True?

2022-01-03 09:33 UTC, michaelosthege commented
> In `pm.set_data()` can we check if it was unmutable and then give an informative error?

I'll make the error message more instructive 👍

> Also, should the default really be mutable=True?

No it shouldn't, but we can't flip that switch at the same time as we're introducing it. That's why I'd first default to showing `pm.ConstantData`/`pm.MutableData`in model graphs (see Slack).
Next step would be a `FutureWarning`.

Should I add the `FutureWarning` already? (When `mutable is None`..)

2022-01-03 09:43 UTC, twiecki commented
Sure, that all sounds good.

On Mon, Jan 3, 2022, 16:33 Michael Osthege ***@***.***> wrote:

> In pm.set_data() can we check if it was unmutable and then give an
> informative error?
>
> I'll make the error message more instructive 👍
>
> Also, should the default really be mutable=True?
>
> No it shouldn't, but we can't flip that switch at the same time as we're
> introducing it. That's why I'd first default to showing pm.ConstantData/
> pm.MutableDatain model graphs (see Slack).
> Next step would be a FutureWarning.
>
> Should I add the FutureWarning already? (When mutable is None..)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pymc-devs/pymc/pull/5295#issuecomment-1003968082>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFETGBEGUAXND3C2QC6SGTUUFUNXANCNFSM5K76572A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-01-04 04:08 UTC, twiecki requested changes
Then we still need the check in `pm.set_data()` if it was immutable.

2022-01-04 08:49 UTC, michaelosthege commented
> Then we still need the check in `pm.set_data()` if it was immutable.

It was there already, line 1132 in model.py

2022-01-04 12:40 UTC, twiecki approved these changes

2022-01-04 12:41 UTC, merged

2022-01-04 12:41 UTC, twiecki commented
:+1: