Refactor `Factor` properties
pymc-devs/pymc pull request #5320
Opened 2022-01-07 12:41 UTC by ricardoV94

This PR deprecates most of the Factor properties, and gives the following default methods:

* compile_logp(self, vars=None, jacobian=True, sum=True):
* compile_dlogp(self, vars=None, jacobian=True):
* compile_d2logp(self, vars=None, jacobian=True):
 
The prefix `compile` is there to make it obvious this is a costly operation, and that the results should be cached once and reused afterwards. Also this makes it easier to deprecate the old properties, which couldn't easily be changed into methods.

It also deprecates `LoosePointFunc` in renames `FastPointFunc` to `PointFunc` which is now the default. This closes #5318.

Finally this PR also renames `pm.logpt` to `pm.joint_logpt`, which is now the main bridge between `PyMC` and `Aeppl`. The reason for this is that `pm.logpt` has diverged quite a lot from what it was doing in `V3`, and because of that it has a lot of ugly internal logic that should be handled by the `Model` object instead (involving trying to find value variables, transforms and scaling in the tags of the variables). The rename will hopefully help break the dependency that's there for backwards compat and facilitate refactoring in the future.

2022-01-07 23:04 UTC, michaelosthege reviewed
Sorry about that nitpick, but given how much code calls these properties/methods, could you add some type hints?
Even incomplete type hints here can give a lot of mypy coverage, right?

2022-01-07 23:04 UTC, michaelosthege commented on pymc/distributions/logprob.py
> +def joint_logpt(
Can you do a PR with the same rename on `v3`?
The warning in `3.11.5` points users to the function you're renaming here..

2022-01-07 23:04 UTC, michaelosthege commented on pymc/model.py
>          return self.model.fn(self.logpt)
Maybe you did this where possible already, but can't more of the properties/methods that now have a warning follow their own instruction and switch to the other API ?

2022-01-07 23:04 UTC, michaelosthege commented on pymc/model.py
> +    def makefn(self, outs, mode=None, **kwargs):
```suggestion
    def makefn(self, outs: Sequence[Variable], mode=None, **kwargs) -> Callable([Sequence[np.ndarray]], Sequence[np.ndarray]):
```
Is it something like this?

2022-01-07 23:04 UTC, michaelosthege commented on pymc/sampling_jax.py
> -from pymc.distributions import logpt
Was this line unused?

2022-01-07 23:04 UTC, michaelosthege commented on pymc/tuning/starting.py
> +        dlogp_func = lambda x: compiled_dlogp_func(RaveledVars(x, x0.point_map_info))
👍

2022-01-07 23:04 UTC, michaelosthege commented on pymc/model.py
>      def logpt(self):
```suggestion
    def logpt(self) -> Variable:
```
I like the refactor. Adding more type hints will make it easier for beginners like me who can't remember which property is a variable and which one is a function...

2022-01-08 06:32 UTC, ricardoV94 commented on pymc/distributions/logprob.py
> +def joint_logpt(
For joint_logpt? That one has no good equivalent in V3. Here we are a advising people to use a new V4 model method (logp_elemwise)

2022-01-08 06:34 UTC, ricardoV94 commented on pymc/model.py
>          return self.model.fn(self.logpt)
I thought that would be more bug prone and difficult to review.

2022-01-08 06:35 UTC, ricardoV94 commented on pymc/model.py
> +    def makefn(self, outs, mode=None, **kwargs):
I'll have to check. thanks for the suggestion

2022-01-08 06:36 UTC, ricardoV94 commented on pymc/sampling_jax.py
> -from pymc.distributions import logpt
Let me check again

2022-01-08 07:50 UTC, ricardoV94 commented on pymc/model.py
> +        cost = self.logpt if not jacobian else self.logp_nojact
```suggestion
        cost = self.logpt if jacobian else self.logp_nojact
```

2022-01-08 07:53 UTC, ricardoV94 commented on pymc/model.py
> +        return self.model.compile_fn(self.dlogpt2(vars=vars, jacobian=jacobian))
```suggestion
        return self.model.compile_fn(self.dlogp2t(vars=vars, jacobian=jacobian))
```

2022-01-10 08:28 UTC, ricardoV94 commented on pymc/sampling_jax.py
> -from pymc.distributions import logpt
Seems like it was

2022-01-10 15:32 UTC, ricardoV94 commented
Marking as a draft to address #5333 in this PR

2022-01-13 04:03 UTC, twiecki commented on pymc/model.py
>      def logp(self):
So yeah, I would just get rid of all of these.

2022-01-13 11:28 UTC, ricardoV94 commented
Band-aids are now being removed quickly! :adhesive_bandage:

2022-01-13 15:17 UTC, twiecki commented on RELEASE-NOTES.md
> +- `logpt`, `logpt_sum`, `logp_elemwiset` and `nojac` variations were removed. Use `Model.logpt(jacobian=jacobian, sum=sum)` instead.
```suggestion
- `logpt`, `logpt_sum`, `logp_elemwiset` and `nojac` variations were removed. Use `Model.logpt(jacobian=True/False, sum=True/False)` instead.
```

2022-01-13 15:18 UTC, twiecki commented on pymc/model.py
> -class LoosePointFunc:
it's so great that these confusing things finally can go.

2022-01-13 15:19 UTC, ricardoV94 commented on RELEASE-NOTES.md
> +- `logpt`, `logpt_sum`, `logp_elemwiset` and `nojac` variations were removed. Use `Model.logpt(jacobian=jacobian, sum=sum)` instead.
Done

2022-01-13 15:21 UTC, twiecki commented
This is shaping up to be a really nice refactor of some quite obscure code.

2022-01-13 15:33 UTC, ricardoV94 commented
> This is shaping up to be a really nice refactor of some quite obscure code.

Hopefully one will also be less lost when doing autocomplete on a Model to find a method xD

2022-01-14 10:33 UTC, michaelosthege requested changes

2022-01-14 10:33 UTC, michaelosthege commented on pymc/model_graph.py
> +        # TODO: Update these lines, variables no longer have a `logpt` attribute
Is this broken now?

(Update: This code wasn't working before either.)

2022-01-14 10:33 UTC, michaelosthege commented on pymc/model.py
> +        """Compiled log probability density function"""
This needs a more detailed docstring.

2022-01-14 10:33 UTC, michaelosthege commented on pymc/model.py
> +        """Compiled log probability density hessian function"""
This one too

2022-01-14 10:33 UTC, michaelosthege commented on pymc/model.py
> +    ) -> Variable:
Needs a docstring

2022-01-14 10:33 UTC, michaelosthege commented on pymc/model.py
> +    ) -> Variable:
Also here; the name is not self-explanatory.

2022-01-14 10:33 UTC, michaelosthege commented on pymc/tests/test_shared.py
> +            # TODO: This should assert something
```suggestion
```

2022-01-14 10:33 UTC, michaelosthege commented on RELEASE-NOTES.md
> +- `logpt`, `logpt_sum`, `logp_elemwiset` and `nojac` variations were removed. Use `Model.logpt(jacobian=True/False, sum=True/False)` instead.
```suggestion
- `logpt`, `logpt_sum`, `logp_elemwiset` and `nojac` property variations were removed. Use `Model.logpt(jacobian=True/False, sum=True/False)` instead.
```

2022-01-14 10:33 UTC, michaelosthege commented on pymc/model.py
> +        """Compiled log probability density gradient function"""
And here

2022-01-14 10:35 UTC, michaelosthege commented
I'm open to having docstring link to docstrings of the other properties/methods.
We can probably make the necessary changes all as suggestions and have one commit for them?

2022-01-14 10:44 UTC, ricardoV94 commented on pymc/model_graph.py
> +        # TODO: Update these lines, variables no longer have a `logpt` attribute
It was already

2022-01-14 10:50 UTC, ricardoV94 commented
> I'm open to having docstring link to docstrings of the other properties/methods. We can probably make the necessary changes all as suggestions and have one commit for them?

Yeah I think the `compile_*` is better of just directing to the respective methods for the meaning of the variables. Feel free to make changes and force-push to this branch! Won't have time to work on this until next week

2022-01-14 11:43 UTC, michaelosthege approved these changes

2022-01-14 11:48 UTC, merged