Revamp our negative binomial explanation (#5300)
pymc-devs/pymc pull request #5365
Opened 2022-01-17 21:06 UTC by herve-91

**Thank your for opening a PR!**

Depending on what your PR does, here are a few things you might want to address in the description:
+ [ ] what are the (breaking) changes that this PR makes?
+ [ ] important background, or details about the implementation
+ [ ] are the changes—especially new features—covered by tests and docstrings?
+ [ ] [linting/style checks have been run](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Python-Code-Style)
+ [ ] [consider adding/updating relevant example notebooks](https://github.com/pymc-devs/pymc-examples)
+ [ ] right before it's ready to merge, mention the PR in the RELEASE-NOTES.md

2022-01-21 09:52 UTC, michaelosthege reviewed
@ColCarroll does this look good from the math side?

2022-01-21 09:52 UTC, michaelosthege commented on pymc/distributions/discrete.py
> +    before the n-th success, given the probability p of success in each trial. and its pmf is
```suggestion
    If it is parametrized in terms of n and p, the negative binomial describes the probability to have x failures 
    before the n-th success, given the probability p of success in each trial. Its pmf is
```

2022-01-23 04:04 UTC, ericmjl commented
Having used the NB distribution in multiple places, I can confirm that the explanation is correct.

2022-01-23 09:56 UTC, michaelosthege requested changes

2022-01-23 09:56 UTC, michaelosthege commented on pymc/distributions/discrete.py
> +        Gamma distribution mean (mu > 0).
```suggestion
        Gamma distribution mean (mu > 0).
```

2022-01-23 09:56 UTC, michaelosthege commented on pymc/distributions/discrete.py
> +
```suggestion

    .. math::

        f(x \mid n, p) =
           \binom{x + n - 1}{x}
           (p)^n (1 - p)^x

```

2022-01-23 12:21 UTC, michaelosthege approved these changes

2022-01-23 12:22 UTC, merged