fixed numpy docstring for class weibull
pymc-devs/pymc pull request #5466
Opened 2022-02-13 05:29 UTC by ravichikkam

**Thank your for opening a PR!**

Depending on what your PR does, here are a few things you might want to address in the description:
+ [ ] what are the (breaking) changes that this PR makes?
+ [ ] important background, or details about the implementation
+ [ ] are the changes—especially new features—covered by tests and docstrings?
+ [ x] [linting/style checks have been run](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Python-Code-Style)
+ [ ] [consider adding/updating relevant example notebooks](https://github.com/pymc-devs/pymc-examples)
+ [ ] right before it's ready to merge, mention the PR in the RELEASE-NOTES.md

Note: doing numpy doc validation for weibull class in distributions/continuous.py

#DataUmbrellaPyMCSprint

2022-02-13 09:31 UTC, twiecki approved these changes

2022-02-15 23:03 UTC, OriolAbril requested changes
Hi @ravichikkam , thanks for the PR, I hope it was an enjoyable experience. I have two quick comments.

1. Can you add the close figs context to the plot directive as shown in https://pymc-data-umbrella.xyz/en/latest/sprint/docstring_tutorial.html#section-independent-comments?

2. Can you go to https://github.com/pymc-devs/pymc/issues/5459 and comment you are working on the Weibull docstring, Also for future contributions do this _before_ starting to work on that, otherwise we might find two PRs working on the same simultaneously and be forced to discard one of them.

2022-02-15 23:44 UTC, ravichikkam commented
Thanks for the comment. I am very excited to be contributing to open source for the very first time. 
I made the changes to add close-figs context and also made a comment on #5459 on WIP on weibull docstring.
Please let me know if this needs more changes.

2022-02-16 00:06 UTC, OriolAbril approved these changes

2022-02-16 00:07 UTC, merged

2022-02-16 00:08 UTC, OriolAbril commented
Thanks @ravichikkam!