Find instances of rv.logp(x) in PyMC and correct to pm.logp(rv,x)
pymc-devs/pymc pull request #5504
Opened 2022-02-19 19:47 UTC by LucyJimenez

xref https://github.com/pymc-devs/pymc/issues/5051
On this PR `rv.logp(x)` was replaced by `pm.logp(rv,x)`.

2022-02-20 02:49 UTC, OriolAbril commented
Thanks for the PR! I have asked someone more familiar with the issue to review. I think that those instances should not be updated as it looks like they are used to write error messages or deprecation warnings for people trying to use the old way so they get something informative saying something along the lines of "rv.logp is deprecated, use pm.logp(rv) instead"

2022-02-20 08:36 UTC, ricardoV94 requested changes
Yes these lines shouldn't be changed. The original issue referred to possible uses in the documentation. Apologies if that was not clear.

2022-02-20 13:09 UTC, LucyJimenez commented
Thanks @OriolAbril and @ricardoV94 for the explanations. I have been checking all the files and found no matches with `rv.logp(x)`, is it possible that I am missing something?

2022-02-20 13:15 UTC, ricardoV94 commented
> Thanks @OriolAbril and @ricardoV94 for the explanations. I have been checking all the files and found no matches with `rv.logp(x)`, is it possible that I am missing something?

Have you looked for stuff like `pm.Normal.dist().logp(...)`. The `rv.logp(x)` is just a template, not the actual code that may or not exist.

Things might also be spread across different lines:
```python
with pm.Model() as m:
  x = pm.Normal("x")

x.logp(...)
```

Basically if you see something like `.logp(x)` and it is not using `pm.logp(x, y)`, it's the old API and needs to be updated.

It's also possible that there are no uses left in the documentation, and we can just close the issue.

2022-02-20 13:29 UTC, ricardoV94 commented
For example this guide is still outdated: https://github.com/pymc-devs/pymc/blob/99ec0ff93362a6d6eba90cbad49a2338c353eccd/docs/source/guides/Probability_Distributions.rst

But it's not a simple fix either...

2022-02-20 14:25 UTC, LucyJimenez commented
@ricardoV94 thank you for all the resources. I'm going to check it more carefully and getting back with questions ;)

2022-02-20 17:08 UTC, OriolAbril commented
@LucyJimenez I checked for instances of logp, logcdf and random _method_ usage and found ocurrences in only 3 files: the developer guide, `PyMC_and_Aesara` one and `Probability_Distributions` that was mentioned by @ricardoV94 above. All 3 explain PyMC distributions, how they are structured into classes, it's methods and the class internals. All three are outdated and refer to version 3 and only the last two are excluded from the docs right now.

It doesn't make much sense to update the code only in these files, both code an explanations need to be updated and that can only be done by someone who understands the new v4 internals (not yet documented anywhere). We should have closed the issue when we updated the notebooks inside the "Learning" section in https://github.com/pymc-devs/pymc/pull/5269 instead of labeling it as recommended issue for the sprint, sorry about that. I'll go close it now. 

You'll have to find another issue to work on. Don't hesitate to tag me on Data Umbrella discord (`@Oriol Abril Pla` there) if you want to have a quick chat/call to find a new issue and get started on it.

2022-02-21 15:02 UTC, LucyJimenez commented
@OriolAbril Thank you for clarifying the general situation. Considering your comment, I will leave this PR free and look for you on discord.

2022-02-22 04:06 UTC, OriolAbril commented
Perfect, I'll try to check Discord a couple times a day to make sure I don't miss your messages.

2022-02-23 09:55 UTC, closed without merging