Removes BART
pymc-devs/pymc pull request #5566
Opened 2022-03-08 10:12 UTC by aloctavodia

This removes BART from the main PyMC codebase in favor of moving it to [pymc-experimental.](https://github.com/pymc-devs/pymc-experimental)

2022-03-08 10:56 UTC, ricardoV94 commented
We need to remove the test_file from the pytest workflow:

https://github.com/pymc-devs/pymc/blob/afe210acc8b90fef718eb4d28da641996c278c91/.github/workflows/pytest.yml#L80

https://github.com/pymc-devs/pymc/blob/afe210acc8b90fef718eb4d28da641996c278c91/.github/workflows/pytest.yml#L66

2022-03-08 10:57 UTC, ricardoV94 commented
What about the competence? Is there a level above `Ideal` that we can give to Bart variables?

2022-03-09 09:08 UTC, ricardoV94 commented
Can you give more context what changes with this commit? https://github.com/pymc-devs/pymc/commit/159e7bfe059ff9c866095c555346ae83e7ef7805

2022-03-09 10:06 UTC, ricardoV94 reviewed
Looks good,

Can you add a test for the step methods change, that shows you can add a step method externally?

Also can you split the bart changes from the step/methods assignment into 2 distinct commits (or PRs)?

2022-03-09 14:00 UTC, aloctavodia commented
What should I do to split the changes into 2 distinct commits (or PRs)?

2022-03-09 14:43 UTC, ricardoV94 commented
> What should I do to split the changes into 2 distinct commits (or PRs)?

git interactive rebase -> reorder + squash all the commits into two commits: 1) remove bart and 2) step method changes

2022-03-09 14:45 UTC, ricardoV94 commented
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

2022-03-09 15:43 UTC, ricardoV94 requested changes
Looks great.

Can you change the commit messages to have a more descriptive title/messages? You don't need to include the titles of the squashed commits unless you want to. This can be done with interactive rebase + reword command

2022-03-09 15:43 UTC, ricardoV94 commented on pymc/sampling.py
> +<<<<<<< HEAD
Some conflict lines here

2022-03-09 15:48 UTC, aloctavodia commented
I was confused with how to change the messages. Now I think I got it right.

2022-03-09 15:50 UTC, ricardoV94 commented on pymc/sampling.py
> +    step = assign_step_methods(model, step, methods=pm.STEP_METHODS, step_kwargs=kwargs)
Does it still add all variables to NUTS when that's possible? If so, any idea why we had this two step strategy before?

2022-03-09 16:19 UTC, aloctavodia commented on pymc/sampling.py
> +    step = assign_step_methods(model, step, methods=pm.STEP_METHODS, step_kwargs=kwargs)
Besides the tests, I run a few models manually and assignment seems to be working properly both when only NUTS is used or when we have more than one sampler.

2022-03-09 16:23 UTC, ricardoV94 approved these changes
Looks great. Award for best branch name! Just checking what is going on with read the docs failure

2022-03-10 08:22 UTC, merged

2022-03-10 08:23 UTC, ricardoV94 commented
I merged it but just realized we need to mention it in the release notes @aloctavodia