Updated convert_shape and convert_size
pymc-devs/pymc pull request #5601
Opened 2022-03-16 07:45 UTC by 5hv5hvnk

this is another PR for #5417  which I got closed because of deletion of my forked repo

```convert_size```  wrongly assumes symbolic sizes have to be scalars
```
import pymc as pm
import aesara.tensor as at

s = at.scalar('s')
size = at.stack([s, s])
x = at.random.normal(size=size)
x.eval({s: 2})
# array([[-0.66285345,  0.97341598],
#        [ 0.05158132,  2.03399059]])

pm.Normal.dist(size=size)
# ValueError: The `size` parameter must be a tuple, TensorVariable, int or list. Actual: <class 'aesara.tensor.var.TensorVariable'>
```

fixed by changing code in 
https://github.com/pymc-devs/pymc/blob/915592235ea6920689f89bece48e2d679e8ed4f1/pymc/distributions/shape_utils.py#L475

by accepting ```size.ndim == 1``` as well as ```size.ndim == 0```

Closes #5394

2022-03-16 07:51 UTC, 5hv5hvnk commented
@twiecki @michaeloriordan please have a look

2022-03-16 09:13 UTC, michaelosthege requested changes
Good call, @5hv5hvnk to just make a new PR.

Please address thecomments & run the pre-commit before I trigger the CI

2022-03-16 09:13 UTC, michaelosthege commented on pymc/distributions/shape_utils.py
> +    elif isinstance(shape, int) or (isinstance(size, TensorVariable) and shape.ndim == 0):
```suggestion
    elif isinstance(shape, int) or (isinstance(shape, TensorVariable) and shape.ndim == 0):
```

2022-03-16 09:13 UTC, michaelosthege commented on pymc/distributions/shape_utils.py
> +        raise ValueError(f"The `size` parameter must be a tuple, TensorVariable, int or list. Actual: {type(size)}")
Do you have some kind of auto-formatting in your editor?
I'm pretty sure this is going to fail the `black` step in our pre-commit. The f-string is the same as before.

2022-03-16 09:13 UTC, michaelosthege commented on pymc/distributions/shape_utils.py
> +
Also this added line will fail the pre-commit.

2022-03-16 17:06 UTC, 5hv5hvnk commented
This failed Arviz compatibility checks, I manually updated Arviz but can't commit because there are no changes in any of the files, how can I fix this?

2022-03-16 17:27 UTC, michaelosthege commented
> This failed Arviz compatibility checks, I manually updated Arviz but can't commit because there are no changes in any of the files, how can I fix this?

This is a rather new problem in our CI pipeline. I think I know how to fix it.
I'll check out your branch and add the fix. Otherwise your changes look fine and I'm optimistic that we can merge it if my CI fix works.

2022-03-16 17:42 UTC, michaelosthege commented
I force-pushed your branch after squashing your two commits.
This way we can do a rebase-merge that'll add these two logically distinct commits to our `main` branch.

However, it looks like GitHub Actions is currently down (https://githubstatus.com).
Let's see when it comes back and if the CI works out this time.

Your PR is most likely the next one that'll get merged 👍

2022-03-17 01:02 UTC, michaelosthege approved these changes

2022-03-17 01:02 UTC, merged