[WIP] Deprecate remaining VI methods
pymc-devs/pymc pull request #5642
Opened 2022-03-22 13:06 UTC by purna135

Addressing #5581

Replaced remaining NotImplementedInference methods with deprecation warning.

2022-03-22 17:00 UTC, purna135 commented
I need some help with the next step; is adding a deprecation warning the right way to go?

2022-03-23 01:09 UTC, cfonnesbeck commented
I think the idea was to just remove them (even though the title in the issue says "deprecate"). The methods are not implemented in v4, so there is really nothing to deprecate.

2022-03-26 18:11 UTC, purna135 commented
Could you please help me remove the Normalizing flows?
I'm not sure if I should remove the entire NormalizingFlowGroup class or just a few lines of code.

https://github.com/pymc-devs/pymc/blob/ef5f91b41d733c64cf3ea785ec2760caae5d1bd4/pymc/variational/approximations.py#L362-L364

2022-04-17 23:34 UTC, canyon289 commented
@ferrine would you like to take a look here?

2022-04-22 16:44 UTC, ferrine reviewed
As for normalizing flows I expect something like `rm pymc/variational/flows.py` as a good first step

2022-04-22 16:44 UTC, ferrine commented on pymc/variational/approximations.py
> +                "Deterministic sampling from a Histogram is deprecated and will be removed soon.",
Is it indeed broken or it was a false alarm?

2022-04-22 16:44 UTC, ferrine commented on pymc/variational/approximations.py
> +                "Deterministic sampling from a Histogram is deprecated and will be removed soon.",
We can enable the test for that and check

2022-04-22 16:44 UTC, ferrine commented on pymc/variational/opvi.py
>          if self.local:
I think the context of the issue was to entirely delete the code and `local` kwarg, feel free to just delete large portions of the code.

2022-04-22 16:44 UTC, ferrine commented on pymc/variational/opvi.py
>          if self.batched:
Same for `batched` kwarg and all its mentions. Just delete without hesitations

2022-04-23 19:23 UTC, fonnesbeck commented
Is this enough to go on @purna135 ?

2022-04-23 19:28 UTC, purna135 commented
I'll work on these suggestions and let you know if I need anything else.
Thank you very much.

2022-05-21 19:52 UTC, michaelosthege commented
Hi @purna135, this PR is one of the final steps towards `v4.0.0`. Could you pick it up again and push it over the finish line?

2022-05-21 19:59 UTC, purna135 commented
Hi @michaelosthege sorry for the delay; I was preoccupied with my exam, which has now been done.
I will complete this RP in few days.

2022-05-22 11:12 UTC, twiecki commented on pymc/variational/opvi.py
> +            warnings.warn("Local inferene aka AEVB is deprecated.", DeprecationWarning)
We should just delete this code, rather than deprecate.

2022-05-23 11:21 UTC, purna135 commented
Hi @twiecki and @ferrine could you please have a look if this is the right way to go?

2022-05-24 10:55 UTC, ferrine approved these changes
Looks good to me, can be merged once tests pass

2022-05-24 11:34 UTC, purna135 commented
Thank you very much, @ferrine. Could you kindly advise me on how to pass these failed tests?
In the doc string, I realised I left some references to `batched` and `local`, which I will remove in my next commit.

2022-05-24 11:59 UTC, ferrine commented
@purna135, the tests diff was collapsed. I think I missed something here. I have to go through it once more

2022-05-24 13:06 UTC, ferrine commented on pymc/tests/test_variational_inference.py
> -@ignore_not_implemented_inference
the `ignore_not_implemented_inference` hook was used to ignore tests that fail due to the not supported functionality. 

`NotImplementedInference` is an explicit error not to confuse failures with other "bugs". Most of the tests that are deleted so far are valid tests. 

The commit that deletes all these tests should be reverted. Or, if not easy, you can use the original file that is present in master.

To summarise. 

1. The only obsolete thing in the test file is `ignore_not_implemented_inference`. 
2. Once it is removed, all tests should pass and no `NotImplementedInference` is raised.
3. The only tests to remove are that fail because of the removed functionality.

2022-05-24 13:07 UTC, ferrine requested changes
I missed the collapsed diff of tests. Most of the deleted tests are valid. I've left a comment above with the explanation.

2022-05-24 14:26 UTC, ferrine commented
We did a quick video chat with @purna135 to avoid further confusion. Additional thing to revisit was the documentation. That missed my eye as well.

2022-05-24 14:30 UTC, purna135 commented
Thank you so much for your time and help @ferrine : )

2022-05-25 18:34 UTC, purna135 commented
Hello, @ferrine. I deleted several flow-related tests and refactored others, but there are still 10 tests that I am unable to refactor and have commented so that other tests can be checked. Could you please assist me in refactoring the tests I commented? 
Many thanks

2022-05-25 19:24 UTC, closed without merging