Update dev guide
pymc-devs/pymc pull request #5810
Opened 2022-05-26 20:16 UTC by michaelosthege

I went over the files under `/docs/source/contributing/*` except the ones that had an `:orphan:` line at the top.

I wrote the instructions on running the test suite and fixed typos in several places.

For the guide on implementing distributions I updated it to the best of my knowledge, but here @ricardoV94 should fact-check me.

Closes #5346

-----

Some remarks that generalize to other pages:
* I changed the formatting of "Project" and "`packages`" to be consistent w.r.t. capitalization and style:
  * NumPy or `numpy`
  * SciPy or `scipy`
  * PyMC or `pymc`
  * Aesara or `aesara`
* Instead of "PyMC `4.x`" we should write "PyMC `>=4.0.0`" so we don't have to update these lines with the next major release.
* cc @OriolAbril I would generally prefer a "one line per sentence" rule in the docs sources, because it makes the `git diff` a lot easier to work with. (Only double line-breaks become line breaks in the rendered output.)

2022-05-26 20:31 UTC, OriolAbril commented
> cc @OriolAbril I would generally prefer a "one line per sentence" rule in the docs sources, because it makes the git diff a lot easier to work with. (Only double line-breaks become line breaks in the rendered output.)

That is perfectly fine with me, I also prefer this style generally

> except the ones that had an :orphan: line at the top.
>
> Closes https://github.com/pymc-devs/pymc/issues/5346

To close the issue all pages should be updated, independently of having `:orphan:` or not. afaik, all pages are currently present in one of the multiple toctrees and show in the left sidebar, the orphan tags are inherited and left in the pages that still have not been touched yet. Most relevant on this and to close this issue is https://docs.pymc.io/en/latest/contributing/developer_guide.html.

2022-05-26 21:13 UTC, ricardoV94 requested changes
The developer distribution part looks good, just an issue with mentioning aeppl

2022-05-26 21:13 UTC, ricardoV94 commented on docs/source/contributing/developer_guide_implementing_distribution.md
> +1. It's okay to use the `rng_fn` `classmethods` of other Aesara, aeppl and PyMC `RandomVariables` inside the new `rng_fn`. For example if you are implementing a negative HalfNormal `RandomVariable`,
```suggestion
1. It's okay to use the `rng_fn` `classmethods` of other Aesara and PyMC `RandomVariables` inside the new `rng_fn`. For example if you are implementing a negative HalfNormal `RandomVariable`, your `rng_fn` can simply return `- halfnormal.rng_fn(rng, scale, size)`.
```

Aeppl doesn't implement any RVs

2022-05-26 22:01 UTC, michaelosthege commented
@ricardoV94 I updated the beginning of the `developer_guide.rst` to something that's hopefully correct and more accessible to people without a strong math background (please check).

I stopped where it got more detailed on `logp`. Can you take over from there?

Large parts of that document are written in the "I" perspective and talk about things that are no longer relevant.

Generally, I would prefer to delete large sections instead of keeping things that are outdated or misleading.

We could also move some submodule-specific developer documentation such as the "Dynamic HMC" or "Variational Inference" sections into `README.md` files that are located in the corresponding subfolders.
Maybe that would help to keep them aligned with the implementation while keeping the docs focused on user API ?

2022-05-27 11:05 UTC, OriolAbril reviewed
> We could also move some submodule-specific developer documentation such as the "Dynamic HMC" or "Variational Inference" sections into README.md files that are located in the corresponding subfolders.
Maybe that would help to keep them aligned with the implementation while keeping the docs focused on user API ?

I always advocate for having documentation in the docs. Pages outside the "contributing" navbar section have users as target audience, pages inside this section have developers and contributors as target audience. IMO, having the docs close or even in the same file has a negligible effect on keeping them updated when compared to making sure this is done as part of the review process. i.e. even docstrings that are as close as possible to the implementation still end up outdated quite often

cc @danhphan I think this should fix some of the issues you mentioned on the running tests page. Is there something else you think is missing?

2022-05-27 11:05 UTC, OriolAbril commented on docs/source/contributing/developer_guide.rst
>  PyMC Developer Guide
We should get rid of the orphan thing and the comment, and add a target right before the title so we can reference this page easily. In rST targets are

```
.. _developer_guide:
```

2022-05-27 11:05 UTC, OriolAbril commented on docs/source/contributing/developer_guide.rst
> +    x = Normal('x', 0, 1)
```suggestion
.. code-block::

    x = Normal('x', 0, 1)
```

Main comment is the space is needed, otherwise the code isn't shown in the rendered page.

I think the ideal scenario is using the code block directive. The default syntax highlight is python so unless we use code blocks in other languages it doesn't need to be specified. Not 100% sure why the code thing alone works as it should be a role (aka inline formatting) instead of a directive.

ref: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block and https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-code

2022-05-27 11:05 UTC, OriolAbril commented on docs/source/contributing/developer_guide.rst
> +Under the hood, the variables are created through the :method:`~pymc.Distribution.dist` API, which calls the :class:`~aesara.tensor.random.basic.RandomVariable` :class:`~aesara.graph.op.Op` correspon
```suggestion
Under the hood, the variables are created through the :meth:`~pymc.Distribution.dist` API, which calls the :class:`~aesara.tensor.random.basic.RandomVariable` :class:`~aesara.graph.op.Op` corresponding to the distribution.
```

2022-05-27 11:05 UTC, OriolAbril commented on docs/source/contributing/developer_guide.rst
> +At a high level of abstraction, the idea behind ``RandomVariable`` ``Op``s is to create symbolic variables (``TensorVariable``s) that can be associated with the properties of a probability distributi
adding a letter after a closing set of two backticks without a space seems to break rendering

2022-05-27 11:05 UTC, OriolAbril commented on docs/source/contributing/developer_guide_implementing_distribution.md
>  # Implementing a Distribution
the import paths need to be fixed here in multiple places. i.e. `pymc.Distribution` instead of `pymc.distributions.Distribution`

2022-05-27 11:05 UTC, OriolAbril commented on docs/source/contributing/developer_guide_implementing_distribution.md
>  If it is, it should be added to the {doc}`Aesara library <aesara>` first and then imported into the PyMC library.
```suggestion
If it is, it should be added to the {doc}`Aesara library <aesara:index>` first and then imported into the PyMC library.
```

2022-05-28 14:53 UTC, michaelosthege commented on docs/source/contributing/developer_guide.rst
> +    x = Normal('x', 0, 1)
I converted the entire page into Markdown to make it easier to format..

2022-05-28 17:14 UTC, michaelosthege commented on docs/source/contributing/developer_guide.rst
> +At a high level of abstraction, the idea behind ``RandomVariable`` ``Op``s is to create symbolic variables (``TensorVariable``s) that can be associated with the properties of a probability distributi
it works now that it's all in markdown

2022-05-28 18:36 UTC, michaelosthege commented
I formatted the dev guide as a Markdown file to make it easier to update.

I only dealt with the beginning, but I wont have the time to continue with the rest.
Therefore I would recommend to (squash) merge the changes I made so far and continue updating the dev guide in the coming days.

2022-05-30 11:30 UTC, danhphan commented
Hi @OriolAbril I think it looks good now. Thanks mate :)

2022-06-03 10:16 UTC, twiecki commented
Can we merge this?

2022-06-03 12:18 UTC, ricardoV94 commented
The changes to the dev guide look good. We will probably want to merge this with the new document that is being added in #5721 but for now we can keep both.

2022-06-03 12:21 UTC, ricardoV94 commented
Nevermind that file is still too outdated...

2022-06-03 12:26 UTC, twiecki commented
Why is this not a NB?

2022-06-03 12:27 UTC, twiecki commented
Maybe we'll remove it for now?

2022-06-03 13:00 UTC, ricardoV94 commented
> Maybe we'll remove it for now?

Let's keep the file around but not show it in the docs? Is this possible @OriolAbril 
I'll branch of this PR with the remaining commits, as those seem still useful.

2022-06-03 17:54 UTC, OriolAbril commented
> Let's keep the file around but not show it in the docs? Is this possible @OriolAbril

Yes, it is possible, we just need to add

```
---
orphan: true
---
```

at the top of the file and remove it from the toctree in https://github.com/pymc-devs/pymc/blob/main/docs/source/contributing/index.md which seems to have happened already

2022-06-10 18:17 UTC, michaelosthege commented
@OriolAbril can you fix the precommit here?

The passage is written to literally have the URLs in there, but the pre-commit doesn't allow it.

2022-06-10 19:07 UTC, OriolAbril commented
> @OriolAbril can you fix the precommit here?
>
> The passage is written to literally have the URLs in there, but the pre-commit doesn't allow it.

Updated the doc (that I copied over unmodified not long ago while fixing the website and navbar) and added the file to the pre-commit exclusion for the cross-reference task. Here the urls must be present, so it needs to be excluded from that check

2022-06-11 11:45 UTC, michaelosthege commented
/pre-commit run

2022-06-11 16:35 UTC, michaelosthege commented
Ok, so the page is now orphaned, and git conflicts were resolved.

Can we merge now? Because this PR adds new content on contributing pages that were previously filled with ToDo placeholders.

2022-06-11 17:30 UTC, OriolAbril approved these changes

2022-06-11 17:59 UTC, merged