Fix kwargs for model
pymc-devs/pymc pull request #5915
Opened 2022-06-20 17:49 UTC by ferrine

Fixes

```python
with pm.Model(aesara_config=dict(mode="JAX")):
    ...
```

and 

```python
with pm.Model(model=parent):
    ...
```

2022-06-20 17:54 UTC, ricardoV94 commented
I don't think we are using that anywhere...? All functions that end up compiling stuff accept `mode`

2022-06-20 17:58 UTC, ricardoV94 commented
> I don't think we are using that anywhere...? All functions that end up compiling stuff accept `mode`

Meaning we should just remove it if it is indeed never used.

2022-06-20 18:02 UTC, ferrine commented
> > I don't think we are using that anywhere...? All functions that end up compiling stuff accept `mode`
> 
> Meaning we should just remove it if it is indeed never used.

I tried to run VI using Jax and failed to do so (couple of more issues to be solved), I hoped this method would work for me as it was implemented in v3.

2022-06-20 18:05 UTC, ricardoV94 commented
I just know it was removed because of the release notes. I don't know how it was used before and I don't remember seeing it being used anywhere in the library since I started working on it.

You can of course use JAX or NUMBA by setting the global aesara compile flag or passing `mode="JAX"` to `pm.sample` or whichever method you are using.

2022-06-20 18:20 UTC, ricardoV94 commented
I was referring to this line: https://github.com/pymc-devs/pymc/blob/121a5ae0005d7e55cf613fbd8d943e1857e512a3/RELEASE-NOTES.md?plain=1#L125

But maybe it was just renamed, not removed?

2022-06-21 06:53 UTC, ferrine commented
> I was referring to this line:
> 
> https://github.com/pymc-devs/pymc/blob/121a5ae0005d7e55cf613fbd8d943e1857e512a3/RELEASE-NOTES.md?plain=1#L125
> 
> But maybe it was just renamed, not removed? I see it is used in the ContextMeta

I failed to find an issue about this change. Neither removing model nor aesara/theano_config.

2022-06-21 06:55 UTC, ferrine commented
Oh, another query gave this: https://github.com/pymc-devs/pymc/issues/4981

2022-06-21 07:05 UTC, ricardoV94 commented
> Oh, another query gave this: https://github.com/pymc-devs/pymc/issues/4981

Do you think that was a misunderstanding (ignoring the __new__ path)? CC @michaelosthege

2022-06-21 07:37 UTC, ferrine commented
> > Oh, another query gave this: #4981
> 
> Do you think that was a misunderstanding (ignoring the **new** path)? CC @michaelosthege

The arguments might be seem to be unused, but they are passed to `__new__`, if missing in `__init__` you get errors

2022-06-21 07:42 UTC, ricardoV94 commented
> > > Oh, another query gave this: #4981
> > 
> > 
> > Do you think that was a misunderstanding (ignoring the **new** path)? CC @michaelosthege
> 
> The arguments might seem to be unused, but they are passed to `__new__`, if missing in `__init__` you get errors

Yeah, it seems to be the case, and your new tests clearly show it has an effect.

2022-06-21 07:44 UTC, michaelosthege requested changes
Is `__new__` automatically called before `__init__`???

The `theano_config` kwarg was intentionally removed without replacement. It looks like it was forgotten to make changes in `__new__`.

We should
- either re-introduce the kwargs in `__init__` __while raising a `TypeError`__ with instructions to use Aesara config functions directly (like we do in tests)
- XOR remove it also from `__new__`

2022-06-21 11:22 UTC, ferrine commented
> Is `__new__` automatically called before `__init__`???

Yes, it is called before `__init__`. I'm fine to remove `aesara_config`, and keep the `model` kwarg

2022-06-21 15:59 UTC, ricardoV94 commented
> > Is `__new__` automatically called before `__init__`???
> 
> Yes, it is called before `__init__`. I'm fine to remove `aesara_config`, and keep the `model` kwarg

+1 for less magic stuff behind the scenes

2022-07-03 08:38 UTC, michaelosthege approved these changes
I'm not a fan of keeping an API that is seldom used, but it looks like the removal was incomplete and this PR fixes it.

At some point we might want to remove `aesara_config` entirely, but that's out of scope for now.

So let's merge this in order to get `4.1.0` over the finish line?

2022-07-03 10:59 UTC, merged