Bump aesara from 2.7.5 to 2.7.6
pymc-devs/pymc pull request #5970
Opened 2022-07-12 12:30 UTC by keesterbrugge

**What is this PR about?**
Bumping aesara from 2.7.5 to 2.7.6

The reason is that pypi is able to properly extract the dependencies of aesara 2.7.6, but not of 2.7.5, [see this ticket for more info](https://github.com/aesara-devs/aesara/pull/1048). So AFAICT with this change pymc and all it's dependencies will be properly added to our pypi-mirror by just adding pymc to it and will be installable with just `pip install pymc` :D 

Thanks for the awesome library! 

...

**Checklist**
+ [ ] Explain important implementation details 👆
+ [ ] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [ ] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [ ] Are the changes covered by tests and docstrings?
+ [ ] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## Bugfixes / New features
- ...

## Docs / Maintenance
- ...

2022-07-12 17:48 UTC, twiecki approved these changes

2022-07-12 20:59 UTC, michaelosthege requested changes
Looks like there were two breaking API changes not mentioned in the release notes of the patch version. (`at.unbroadcast` and `at.patternbroadcast`)

Did they originate from https://github.com/aesara-devs/aesara/pull/915?
Maybe @ricardoV94 knows how to work around these API breaks?

2022-07-15 06:29 UTC, ricardoV94 commented
I'm taking a look!

2022-07-15 09:25 UTC, michaelosthege approved these changes

2022-07-15 10:33 UTC, merged