SMC: replace multinomial sampling with systematic sampling
pymc-devs/pymc pull request #6162
Opened 2022-09-28 19:18 UTC by aloctavodia

Empirically, systematic sampling has been shown to be systematically ;-) better than multinomial sampling when used for SMC.

2022-09-29 06:04 UTC, ricardoV94 requested changes

2022-09-29 06:04 UTC, ricardoV94 commented on pymc/smc/smc.py
> +    uniform = (np.random.rand(1) + arange) / lnw
This should use a numpy generator for seeding, which is passed to the function (`self.rng` in the case of SMC kernels)

2022-09-29 06:04 UTC, ricardoV94 commented on pymc/smc/smc.py
> +def systematic(weights):
Can we give this a more expressive name? And also test it directly?

2022-09-29 12:30 UTC, ricardoV94 approved these changes

2022-09-29 19:00 UTC, merged

2022-09-30 08:24 UTC, ricardoV94 commented
@aloctavodia you forgot to squash the two commits when merging. No biggie :)

2022-10-01 18:20 UTC, aloctavodia commented
Thanks for the remainder. I completely forgot about that.