Add warning if observed in DensityDist is dict
pymc-devs/pymc pull request #6292
Opened 2022-11-12 16:18 UTC by symeneses

**What is this PR about?**
It adds a warning if the observed parameter is a dictionary.

**Checklist**
+ [ x] Explain important implementation details 👆
+ [ x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x ] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [x ] Are the changes covered by tests and docstrings?
+ [ x] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## Bugfixes / New features
- ...
It solves #6032 
## Docs / Maintenance
- ...

2022-11-12 17:10 UTC, fonnesbeck commented
LGTM. Thanks for contributing!

2022-11-12 17:10 UTC, fonnesbeck approved these changes

2022-11-12 17:42 UTC, michaelosthege approved these changes
just some code style simplifications/FYI

looks good!

2022-11-12 17:42 UTC, michaelosthege commented on pymc/distributions/distribution.py
> +        if "observed" in kwargs.keys() and isinstance(kwargs["observed"], dict):
```suggestion
        if isinstance(kwargs.get("observed", None), dict):
```

2022-11-12 17:42 UTC, michaelosthege commented on pymc/distributions/distribution.py
> +                "The observed parameter should be of type `pd.Series`, " "`np.array`, or `pm.Data`."
```suggestion
                "The observed parameter should be of type `pd.Series`, `np.array`, or `pm.Data`."
```

2022-11-12 17:45 UTC, ricardoV94 requested changes
This is a great start but misses the most important point of the original issue. 

DensityDist is defined differently than how it was in V3 where a dictionary with the other parameters besides data could be used. The error message should address this change in API more than what types of observed data are allowed (that's not what users find confusing).

2022-11-14 15:11 UTC, symeneses commented
Based on this item in the Release notes:
> pm.DensityDist now accepts distribution parameters as positional arguments. Passing them as a dictionary in the observed keyword argument is no longer supported and will raise an error (see 5026).

I am suggesting this new error message:

Since ``v4.0.0`` the ``observed`` parameter should be of type ``pd.Series``, ``np.array``, or ``pm.Data``.
Previous versions allowed passing distribution parameters as a dictionary in ``observed``, in the current version these parameters are positional arguments.

Let me know if this message can be further improved.

2022-11-15 17:40 UTC, michaelosthege approved these changes

2022-11-15 17:41 UTC, merged