Update discrete.py
pymc-devs/pymc pull request #6498
Opened 2023-02-03 19:27 UTC by soma2000-lang

**What is this PR about?**
...

**Checklist**
+ [ ] Explain important implementation details 👆
+ [ ] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [ ] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [ ] Are the changes covered by tests and docstrings?
+ [ ] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## New features
- ...

## Bugfixes
- ...

## Documentation
- ...

## Maintenance
- ...

2023-02-05 12:27 UTC, OriolAbril requested changes

2023-02-05 12:27 UTC, OriolAbril commented on pymc/distributions/discrete.py
> +    Variance  :math:`\dfrac{n \alpha \beta (\alpha+\beta+n)}{(\alpha+\beta)^2 (\alpha+\beta+1)}
The formula needs a closing `` ` `` in order to be rendered properly. Other than that it looks good, thanks!

Here is the preview for this PR: https://pymcio--6498.org.readthedocs.build/projects/docs/en/6498/api/distributions/generated/pymc.BetaBinomial.html

2023-02-07 15:48 UTC, soma2000-lang commented
@OriolAbril It would be great if you can force push the change required ,beacause I somehow messed up with git and had to delete my forked repository ,even the manual edit option is not available.Really Sorry.

Regards

2023-02-08 19:41 UTC, larryshamalama commented
> @OriolAbril It would be great if you can force push the change required ,beacause I somehow messed up with git and had to delete my forked repository ,even the manual edit option is not available.Really Sorry.
> 
> Regards

Hi @soma2000-lang,  I'd thought that I'd provide some steps in recovering your current work in progress. I've also previously ran into the issue that you're currently experiencing.

#### 1. Add upstream

With this pull request created, you should be able to fetch it from the `pymc-devs` PyMC repo as an upstream. Try the following:

```bash
git remote -v # checks your origin and upstream repositories
git remote add upstream https://github.com/pymc-devs/pymc/
```

You may already have the upstream set, so this step may be optional.

#### 2. Fetch pull request

With the upstream set, run the following:

```
git fetch upstream pull/6498/head:patch-1
```

#### 3. Checkout

```
git checkout patch-1
```

After the checkout, you should find yourself back on the branch here and can now continue making edits.

Let us know if you have any questions!

2023-02-08 19:43 UTC, soma2000-lang commented
Thanks @larryshamalama I will try

2023-02-11 19:04 UTC, closed without merging