Implemented logprob for SpecifyShape and CheckandRaise
pymc-devs/pymc pull request #6538
Opened 2023-02-20 12:36 UTC by Dhruvanshu-Joshi

**What is this PR about?**
With this PR, I intend to close the issue [6352](https://github.com/pymc-devs/pymc/issues/6352).
I have implemented logprob for SpecifyShape and CheckandRaise and also included a rewrite that converts a SpecifyShape or CheckandRaise of a MeasurableVariable into a MeasurableSpecifyShape/Assert Op.
I have also modified the init file to be consistent with the modifications.

**Checklist**
+ [x] Explain important implementation details 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [x] Are the changes covered by tests and docstrings?
+ [x] Fill out the short summary sections 👇

## Major / Breaking Changes
- no

## New features
- Created a file to implement logprob for SpecifyShape by transfering specify_shape from rv to value and included a rewrite that converts a SpecifyShape of a MeasurableVariable into a MeasurableSpecifyShape Op.
- Created a file to implement logprob for CheckandRaise. If the assertion is true, the value variable will retain its value and if its false, a ValueError will be raised. Also have included a rewrite that converts a CheckandRaise of a MeasurableVariable into a MeasurableAssert Op.

## Bugfixes
- no

## Documentation
- Documentation has been updated consistent with modifications

## Maintenance
- no

2023-02-20 13:58 UTC, ricardoV94 requested changes
Looks great! Just some renaming suggestion.

More importantly, we need tests :)

2023-02-20 13:58 UTC, ricardoV94 commented on pymc/logprob/check_raise_assert.py
> +class MeasurableAssert(CheckAndRaise):
Let's use the same name as the original class everywhere, including in the other functions in this file

```suggestion
class MeasurableCheckAndRaise(CheckAndRaise):
```

And let's call this file `raise_op` like the pytensor one

2023-02-21 11:30 UTC, Dhruvanshu-Joshi commented
Hey @ricardoV94  I did try including test but I think I'll need some help. From what I understand, we'll just have to import the function ```logprob_specify_shape``` into the test file and use it on some ```op``` and ```inner_rv``` to specify its shape and generate the logprob. Lastly, we'll need a assert to verify if the log-likelihood for this and expected matches or not. Somehow, I am not able to implement this. I did try referring ```test_cumsum``` but got more confused. Can you provide some sample examples/resources to get me started in the right direction. Thanks!

2023-02-21 11:45 UTC, ricardoV94 commented
Usually we test a bit more high-level. 
1. Create the generative graph which uses the new Op that we support the logprob for now
2. Obtain the logprob
3. Test the logprob

Something like this for the SpecifyShape (untested code):
```python
import numpy as np
import pytensor
import pytensor.tensor as pt
from scipy import stats

from pymc.distributions import Dirichlet
from pymc.logprob.joint_logprob import factorized_joint_logprob

def test_specify_shape_logprob():
  x_base = Dirichlet.dist(np.ones((3,)), shape=(5, 3)),
  x_rv = pt.specify_shape(x_base, shape=(5, 3))
  x_rv.name = "x"

  x_vv = x_rv.clone()
  [x_logp] = factorized.joint_logprob({x_rv: x_vv}).values()

  x_logp_fn = pytensor.function([x_vv], x_logp)

  # Test valid logp
  x_vv_test = stats.dirichlet(np.ones((3,))).rvs(size=(5,))
  np.testing.assert_array_almost_equal(x_logp_fn(x_vv_test), stats.dirichlet(np.ones((3,))).logpdf(x_vv_test))
  
  # Test shape error
  x_vv_test_invalid = stats.dirichlet(np.ones((1,))).rvs(size=(5,))
  with pytest.raises(ValueError, match=...):
    x_logp_fn(x_vv_test_invalid)
```

2023-03-01 15:03 UTC, Dhruvanshu-Joshi commented
Hey @ricardoV94 I tried generating the tests referring the above code block. But the ```pt.specify_shape``` function is causing error when requesting the log-prob using ```factorized_joint_logprob```. The problem is that the output in the node and the updated_rv from the map do not match. This is not a problem if ```specify_shape``` is not used. Can you please help me with this?

2023-03-01 20:13 UTC, Dhruvanshu-Joshi commented
Yeah sure! I was just experimenting and trying to understand the same code as above hence did not make any major changes.
```
import numpy as np
import pytensor
import pytensor.tensor as pt
from scipy import stats
import pymc as pm

from pymc.distributions import Dirichlet
from pymc.logprob.joint_logprob import factorized_joint_logprob

def test_specify_shape_logprob():
  # 1. Create graph using SpecifyShape
  # Use symbolic last dimension, so that SpecifyShape is not useless
  last_dim = pt.scalar(name="last_dim", dtype="int64") 
  x_base = Dirichlet.dist(pt.ones((last_dim,)), shape=(5, last_dim))
  x_base.name = "x"
  x_rv = pt.specify_shape(x_base, shape=(5, 3))
  x_rv.name = "x"

  # 2. Request logp
  x_vv = x_rv.clone()
  [x_logp] = factorized_joint_logprob({x_rv : x_vv}).values()

  # 3. Test logp
  x_logp_fn = pytensor.function([x_vv], x_logp)

  # 3.1 Test valid logp
  x_vv_test = stats.dirichlet(np.ones((3,))).rvs(size=(5,))
  np.testing.assert_array_almost_equal(
    x_logp_fn(last_dim=3, x=x_vv_test), 
    stats.dirichlet(np.ones((3,))).logpdf(x_vv_test),
  )
  
  # 3.2 Test shape error
  x_vv_test_invalid = stats.dirichlet(np.ones((1,))).rvs(size=(5,))
  with pytest.raises(ValueError, match=...):
    x_logp_fn(last_dim=1, x=x_vv_test_invalid)
if __name__=="__main__":
    test_specify_shape_logprob()
    
 ```

2023-03-06 08:24 UTC, ricardoV94 commented
@Dhruvanshu-Joshi There were some issues in `find_measurable_specify_shapes`. I found them going into the interactive debugger and seeing which lines failed. I pushed a commit that fixes it.

Also need to tweak the test. Let me know if the changes help to understand what was wrong, and if you want to proceed with testing (and possibly fixing remaining errors) on the measurable assert part.

2023-03-08 17:03 UTC, Dhruvanshu-Joshi commented
Hey @ricardoV94 I have made changes to the ```check_raise_assert.py``` in accordance with the [commit](https://github.com/pymc-devs/pymc/pull/6538/commits/983f2ddcfb9c0358f9bd49ba13cb252086e67a6b) . I am also in process of creating a test for it as done in the above commit. This is the skeleton of what I think must be done here:
```
import re
import numpy as np
import pytensor
import pytensor.tensor as pt
import pytest

from scipy import stats

from pymc.distributions import Dirichlet
from pymc.logprob.joint_logprob import factorized_joint_logprob
from tests.distributions.test_multivariate import dirichlet_logpdf


def test_check_raise_assert():
    # 1. Create graph using SpecifyShape
    # Use symbolic last dimension, so that SpecifyShape is not useless
    last_dim = pt.scalar(name="last_dim", dtype="int64")
    x_base = Dirichlet.dist(pt.ones((last_dim,)), shape=(5, last_dim))
    x_base.name = "x"
    assert_op = Assert("This assert failed")
    x_rv = x_base.clone()
    x_rv.name = "x"

    # 2. Request logp
    x_vv = x_rv.clone()
    [x_logp] = factorized_joint_logprob({x_rv: x_vv}).values()

    # 3. Test logp
    x_logp_fn =  pytensor.function([x_logp], assert_op(x_logp, x_logp.size < 2)
```
I'll need a little help in ```3.1 Test valid logp``` and ```3.2 Test shape error``` part of the code .

2023-03-08 17:04 UTC, Dhruvanshu-Joshi commented
Also when I try to run ```python test_specify_shape``` in git-bash, I encounter this huge error:
```
$ python test_specify_shape.py
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding
ERROR (pytensor.graph.rewriting.basic): node: InplaceDimShuffle{}(TensorConstant{(1,) of 3})
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pytensor\graph\rewriting\basic.py", line 1925, in process_node
    replacements = node_rewriter.transform(fgraph, node)
  File "C:\Python310\lib\site-packages\pytensor\graph\rewriting\basic.py", line 1084, in transform
    return self.fn(fgraph, node)
  File "C:\Python310\lib\site-packages\pytensor\tensor\rewriting\basic.py", line 1141, in constant_folding
    thunk = node.op.make_thunk(node, storage_map, compute_map, no_recycling=[])
  File "C:\Python310\lib\site-packages\pytensor\link\c\op.py", line 131, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
  File "C:\Python310\lib\site-packages\pytensor\link\c\op.py", line 96, in make_c_thunk
    outputs = cl.make_thunk(
  File "C:\Python310\lib\site-packages\pytensor\link\c\basic.py", line 1202, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "C:\Python310\lib\site-packages\pytensor\link\c\basic.py", line 1122, in __compile__
    thunk, module = self.cthunk_factory(
  File "C:\Python310\lib\site-packages\pytensor\link\c\basic.py", line 1647, in cthunk_factory
    module = cache.module_from_key(key=key, lnk=self)
  File "C:\Python310\lib\site-packages\pytensor\link\c\cmodule.py", line 1231, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Python310\lib\site-packages\pytensor\link\c\basic.py", line 1546, in compile_cmodule
    module = c_compiler.compile_str(
  File "C:\Python310\lib\site-packages\pytensor\link\c\cmodule.py", line 2641, in compile_str
    raise CompileError(
pytensor.link.c.exceptions.CompileError: Compilation failed (return status=1):
"C:\MinGW\bin\g++.exe" -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -Wno-c++11-narrowing -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"C:\Python310\lib\site-packages\numpy\core\include" -I"C:\Python310\include" -I"C:\Python310\lib\site-packages\pytensor\link\c\c_code" -L"C:\Python310\libs" -L"C:\Python310" -o "C:\Users\Admin\AppData\Local\PyTensor\compiledir_Windows-10-10.0.22000-SP0-Intel64_Family_6_Model_140_Stepping_1_GenuineIntel-3.10.7-64\tmpu6ccrda8\mdb3a1a186c6e0c789bc6494774a591ac6d8ab11d3ed19bf02a4ff96ab64fa9ba.pyd" "C:\Users\Admin\AppData\Local\PyTensor\compiledir_Windows-10-10.0.22000-SP0-Intel64_Family_6_Model_140_Stepping_1_GenuineIntel-3.10.7-64\tmpu6ccrda8\mod.cpp" "C:\Python310\python310.dll"
C:\Users\Admin\AppData\Local\PyTensor\compiledir_Windows-10-10.0.22000-SP0-Intel64_Family_6_Model_140_Stepping_1_GenuineIntel-3.10.7-64\tmpu6ccrda8\mod.cpp:1:0: sorry, unimplemented: 64-bit mode not compiled in
 #include <Python.h>



ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding
ERROR (pytensor.graph.rewriting.basic): node: InplaceDimShuffle{}(TensorConstant{(1,) of 3})
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pytensor\graph\rewriting\basic.py", line 1925, in process_node
    replacements = node_rewriter.transform(fgraph, node)
  File "C:\Python310\lib\site-packages\pytensor\graph\rewriting\basic.py", line 1084, in transform
    return self.fn(fgraph, node)
  File "C:\Python310\lib\site-packages\pytensor\tensor\rewriting\basic.py", line 1141, in constant_folding
    thunk = node.op.make_thunk(node, storage_map, compute_map, no_recycling=[])
  File "C:\Python310\lib\site-packages\pytensor\link\c\op.py", line 131, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
  File "C:\Python310\lib\site-packages\pytensor\link\c\op.py", line 96, in make_c_thunk
    outputs = cl.make_thunk(
  File "C:\Python310\lib\site-packages\pytensor\link\c\basic.py", line 1202, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "C:\Python310\lib\site-packages\pytensor\link\c\basic.py", line 1122, in __compile__
    thunk, module = self.cthunk_factory(
  File "C:\Python310\lib\site-packages\pytensor\link\c\basic.py", line 1647, in cthunk_factory
    module = cache.module_from_key(key=key, lnk=self)
  File "C:\Python310\lib\site-packages\pytensor\link\c\cmodule.py", line 1231, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Python310\lib\site-packages\pytensor\link\c\basic.py", line 1546, in compile_cmodule
    module = c_compiler.compile_str(
  File "C:\Python310\lib\site-packages\pytensor\link\c\cmodule.py", line 2641, in compile_str
    raise CompileError(
pytensor.link.c.exceptions.CompileError: Compilation failed (return status=1):
"C:\MinGW\bin\g++.exe" -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -Wno-c++11-narrowing -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"C:\Python310\lib\site-packages\numpy\core\include" -I"C:\Python310\include" -I"C:\Python310\lib\site-packages\pytensor\link\c\c_code" -L"C:\Python310\libs" -L"C:\Python310" -o "C:\Users\Admin\AppData\Local\PyTensor\compiledir_Windows-10-10.0.22000-SP0-Intel64_Family_6_Model_140_Stepping_1_GenuineIntel-3.10.7-64\tmpbadr0mff\mdb3a1a186c6e0c789bc6494774a591ac6d8ab11d3ed19bf02a4ff96ab64fa9ba.pyd" "C:\Users\Admin\AppData\Local\PyTensor\compiledir_Windows-10-10.0.22000-SP0-Intel64_Family_6_Model_140_Stepping_1_GenuineIntel-3.10.7-64\tmpbadr0mff\mod.cpp" "C:\Python310\python310.dll"
C:\Users\Admin\AppData\Local\PyTensor\compiledir_Windows-10-10.0.22000-SP0-Intel64_Family_6_Model_140_Stepping_1_GenuineIntel-3.10.7-64\tmpbadr0mff\mod.cpp:1:0: sorry, unimplemented: 64-bit mode not compiled in
 #include <Python.h>



ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding
ERROR (pytensor.graph.rewriting.basic): node: InplaceDimShuffle{}(TensorConstant{(1,) of 3})
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pytensor\graph\rewriting\basic.py", line 1925, in process_node
    replacements = node_rewriter.transform(fgraph, node)
  File "C:\Python310\lib\site-packages\pytensor\graph\rewriting\basic.py", line 1084, in transform
    return self.fn(fgraph, node)
  File "C:\Python310\lib\site-packages\pytensor\tensor\rewriting\basic.py", line 1141, in constant_folding
    thunk = node.op.make_thunk(node, storage_map, compute_map, no_recycling=[])
  File "C:\Python310\lib\site-packages\pytensor\link\c\op.py", line 131, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
  File "C:\Python310\lib\site-packages\pytensor\link\c\op.py", line 96, in make_c_thunk
    outputs = cl.make_thunk(
  File "C:\Python310\lib\site-packages\pytensor\link\c\basic.py", line 1202, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "C:\Python310\lib\site-packages\pytensor\link\c\basic.py", line 1122, in __compile__
    thunk, module = self.cthunk_factory(
  File "C:\Python310\lib\site-packages\pytensor\link\c\basic.py", line 1647, in cthunk_factory
    module = cache.module_from_key(key=key, lnk=self)
  File "C:\Python310\lib\site-packages\pytensor\link\c\cmodule.py", line 1231, in module_from_key
    module = lnk.compile_cmodule(location)
  Fil [...]

2023-03-08 17:04 UTC, Dhruvanshu-Joshi commented
As a result I tried to run this in a google colab cell and I encounter an error in line ```[x_logp] = factorized_joint_logprob({x_rv: x_vv}).values()``` stating ```The logprob terms of the following value variables could not be derived: {x}```

2023-03-11 15:50 UTC, Dhruvanshu-Joshi commented
Hey @ricardoV94 . Added the tests and made the changes. Because the folder tests was move outside the ```pymc``` package  we import ```dirichlet_logpdf``` which is defined in ```tests.distributions.test_multivariate``` using the fact that ```tests.logprob``` in which our tests are defined and ```tests.distributions``` lie in the same parent directory.

2023-03-17 22:53 UTC, Dhruvanshu-Joshi commented
Hey @ricardoV94 . The previous commit had some issues related to the mypy tests which are now rectified. Also made some changes in the ```find_measurable_asserts``` and have included the tests too. Please review.

2023-03-20 11:17 UTC, ricardoV94 requested changes
Looks good. Some things:

1. You are adding two binary files accidentaly: `.coverage` and `pymc/.model.py.swn` that must be removed from the PR
2. Let's merge the two functions in `pymc/logprob/checks.py`, and the tests in `tests/logprob/test_checks.py` I think that's more intuitive.
3. You need to add the new test file here: https://github.com/pymc-devs/pymc/blob/473c9528e56fc291e323e30082c8f4295dbd6149/.github/workflows/tests.yml#L92-L102

If the tests pass, that should be it!

2023-03-20 15:05 UTC, Dhruvanshu-Joshi commented
Hey @ricardoV94 . I have incorporated all your suggested changes in the latest commit. Hope this solves the issue.

Also I have noticed that ever since tests was moved outside the pymc package, in every program which inherits any instance from tests, the import ``` from pymc.tests import xyz has been simply replaced with ```from tests import xyz```.
Eg in ```tests\logprob\test_composite_logprob.py```:
```
from pymc.logprob.censoring import MeasurableClip
from pymc.logprob.rewriting import construct_ir_fgraph
from pymc.testing import assert_no_rvs
from pymc.tests.logprob.utils import joint_logprob
```
has been replaced with
```
from pymc.logprob.censoring import MeasurableClip
from pymc.logprob.rewriting import construct_ir_fgraph
from pymc.testing import assert_no_rvs
from tests.logprob.utils import joint_logprob
```
Although this does not cause any problem when running the test_suites using pytest, runnning them naively using ```python test_composite_logprob.py``` causes import issues
As a solution I have used 
```
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0, parentdir)
from distributions.test_multivariate import dirichlet_logpdf
```
I understand this is not a big problem and the solution is a little lengthy. However if you are interested, I would like to explore more methods.
What are your views on including a related solution everywhere where tests is called?

2023-03-22 08:29 UTC, ricardoV94 commented
I think the tests are supposed to be run from the root repository folder. Then you shouldn't have issue with the imports?

2023-03-22 08:34 UTC, ricardoV94 reviewed
Looks good. I left a couple of small suggestions below.

Also note that you seem to have picked/reverted a couple of changes that don't belong to this PR when you merged from the main branch (see the files changed tab). Those have to be cleaned up, before we can merge this PR

2023-03-22 08:34 UTC, ricardoV94 commented on pymc/logprob/checks.py
> +        return None  # pragma: no cover
This isn't needed. The decorator already makes sure the rewrite is only ever called for nodes with Op of the right kind

```suggestion
```

2023-03-22 08:34 UTC, ricardoV94 commented on pymc/logprob/checks.py
> +class MeasurableAssert(CheckAndRaise):
```suggestion
class MeasurableCheckAndRaiseCheckAndRaise):
```

2023-03-22 08:35 UTC, ricardoV94 commented on pymc/logprob/checks.py
> +        return None  # pragma: no cover
Also not needed
```suggestion
```

2023-03-25 09:26 UTC, Dhruvanshu-Joshi commented
> I think the tests are supposed to be run from the root repository folder. Then you shouldn't have issue with the imports?

Even from the root repository if we run the simple command ```python tests/test_model.py``` we face import errors. Running  ```pytest -v tests/test_model.py``` gives no error and works smoothly.

2023-03-25 09:30 UTC, Dhruvanshu-Joshi commented
Hey @ricardoV94 I have included your suggestions in the latest commit. Sorry for the delay as I got caught up in exams and am currently working on my GSOC proposal.
About file changes from other PRs, I have cross-checked and all these changes have been merged into main already and none seem to revert any changes.

2023-03-29 16:05 UTC, ricardoV94 requested changes

2023-03-29 16:05 UTC, ricardoV94 commented on tests/logprob/test_checks.py
> +sys.path.insert(0, parentdir)
This should be removed. For running the test locally, just make sure you are running from the root folder I think
```suggestion
```

2023-03-29 16:19 UTC, Dhruvanshu-Joshi commented
@ricardoV94 I have included this change. Seems like this time only the commit with the actual change shows up by following the steps you provided. Thank you.

2023-03-29 16:59 UTC, ricardoV94 approved these changes
Looks great!

2023-03-29 21:02 UTC, merged