replacing pytensor-devs for aesara-devs
pymc-devs/pymc pull request #6817
Opened 2023-07-04 19:10 UTC by amyoshino

**What is this PR about?**
Closes #6800 

This PR replaces occurrences of `pytensor-devs` for `aesara-devs` in the issues hyperlinks present in docstrings.

What it is replacing?
`pytensor-devs/pytensor` -> `aesara-devs/aesara`
`pytensor-devs/aeppl` -> `aesara-devs/aeppl`

Test:
`grep -r "pytensor-devs"` returns no records

**Checklist**
+ [X] Explain important implementation details 👆
+ [X] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [X] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [X] Are the changes covered by tests and docstrings?
+ [X] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## New features
- ...

## Bugfixes
- ...

## Documentation
- ...

## Maintenance
- ...

2023-07-05 14:49 UTC, larryshamalama requested changes
Thanks @amyoshino for opening your PR :) One minor edit and we should be good to merge!

2023-07-05 14:49 UTC, larryshamalama commented on docs/source/learn/core_notebooks/pymc_pytensor.ipynb
> +    "In this notebook we want to give an introduction of how PyMC models translate to PyTensor graphs. The purpose is not to give a detailed description of all [`pytensor`](https://github.com/aesara-
```suggestion
    "In this notebook we want to give an introduction of how PyMC models translate to PyTensor graphs. The purpose is not to give a detailed description of all [`pytensor`](https://github.com/pymc-devs/pytensor)'s capabilities but rather focus on the main concepts to understand its connection with PyMC. For a more detailed description of the project please refer to the official documentation."
```
My mistake in the original issue. We probably want this to point to the PyTensor repo url

2023-07-05 15:00 UTC, amyoshino commented
Amazing, thanks for the review! I just accepted the suggestion, let me know if something else is missing :)

2023-07-06 01:58 UTC, larryshamalama approved these changes
Looks good to me, thanks for your contribution! :)

2023-07-06 01:59 UTC, merged