Logprob derivation of min
pymc-devs/pymc pull request #6846
Opened 2023-08-06 08:38 UTC by Dhruvanshu-Joshi

**What is this PR about?**
This PR aims to provide a solution for implementing the Max operation from order statistics to solve the issue [#6350](https://github.com/pymc-devs/pymc/issues/6350) and issue [6773](https://github.com/pymc-devs/pymc/issues/6773). This is an extension of [#6769](https://github.com/pymc-devs/pymc/pull/6769). More tests related to MIN operation are to be added.

**Checklist**
+ [x] Explain important implementation details 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [x] Are the changes covered by tests and docstrings?
+ [x] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## New features
- Logprob derivation for ```pt.min```

## Bugfixes
- ...

## Documentation
- ...

## Maintenance
- ...

2023-08-14 14:29 UTC, ricardoV94 requested changes

2023-08-14 14:29 UTC, ricardoV94 commented on pymc/logprob/order.py
> +class MeasurableMin(Max):
Why is this inheriting from `Max`?

2023-08-14 14:29 UTC, ricardoV94 commented on pymc/logprob/order.py
> +    """A placeholder used to specify a log-likelihood for a min sub-graph."""
```suggestion
    """A placeholder used to specify a log-likelihood for a max(neg(x)) sub-graph.
    
    This shows up in the graph of min, which is (neg(max(neg(x))).
    """
```

2023-08-14 14:29 UTC, ricardoV94 commented on pymc/logprob/order.py
> +def find_measurable_min(fgraph: FunctionGraph, node: Node) -> Optional[List[TensorVariable]]:
```suggestion
def find_measurable_max_neg(fgraph: FunctionGraph, node: Node) -> Optional[List[TensorVariable]]:
```

2023-08-14 14:29 UTC, ricardoV94 commented on pymc/logprob/order.py
> +    # Min is the Max of the negation of the same distribution. Hence, op must be Elemiwise
```suggestion
    # Min is the Max of the negation of the same distribution. Hence, op must be Elemwise
```

2023-08-14 14:29 UTC, ricardoV94 commented on pymc/logprob/order.py
> +    # negation is -1*(rv). Hence the scalar_op must be Mul
```suggestion
    # negation is rv * (-1). Hence the scalar_op must be Mul
```

2023-08-14 14:29 UTC, ricardoV94 commented on pymc/logprob/order.py
> +    if not isinstance(base_var.owner.op.scalar_op, Mul):
The check needs to be a bit more exhaustive. Something like:
```suggestion
    try:
        if not (
            isinstance(base_var.owner.op.scalar_op, Mul)
            and len(base_var.owner.inputs) == 2
            and get_underlying_scalar_constant_value(base_var.owner.inputs[1]) == -1
        ):
           return None
    except NotScalarConstantError:
        return None
```

2023-08-14 14:29 UTC, ricardoV94 commented on tests/logprob/test_order.py
> +    if if_max == True:
```suggestion
    if if_max:
```

2023-08-14 14:29 UTC, ricardoV94 commented on tests/logprob/test_order.py
> +def test_non_iid_fails(if_max):
```suggestion
@pytest.mark.parametrize(
    "pt_op",
    [
        pt.max,
        pt.min,
    ],
)
def test_non_iid_fails(pt_op):
```

2023-08-18 12:29 UTC, Dhruvanshu-Joshi commented on pymc/logprob/order.py
> +class MeasurableMin(Max):
Because we handle min as neg(max(neg(x))).

2023-09-02 04:24 UTC, Dhruvanshu-Joshi commented
@ricardoV94 @larryshamalama Is this PR good to be merged or are we left with something here?

2023-09-04 14:18 UTC, ricardoV94 commented on pymc/logprob/order.py
> +def min_logprob(op, values, base_var, **kwargs):
```suggestion
def max_neg_logprob(op, values, base_var, **kwargs):
```

2023-09-04 14:18 UTC, ricardoV94 approved these changes

2023-09-04 15:43 UTC, merged