Fix shape_utils missing functions and misformatted returns
pymc-devs/pymc pull request #7006
Opened 2023-11-10 23:36 UTC by UditNayak

**What is this PR about?**
Fixes #7004 
The shape_utils module was missing functions in the documentation. Additionally, the rendering of returns for certain functions was identified as messy. The focus of this PR is to include type hints in the docstring, in line with the suggested improvement.

**Checklist**
+ [x] Explain important implementation details 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [x] Are the changes covered by tests and docstrings?
+ [x] Fill out the short summary sections 👇

## Documentation
- Added shape_utils missing functions to documentation
- Improved return formatting for the affected functions to enhance readability.
- Included type hints in the docstring for better display in the documentation.

![image](https://github.com/pymc-devs/pymc/assets/142026166/9d206f58-e1bb-48f9-a645-a0b1d5bbda66)

2023-11-11 00:44 UTC, twiecki approved these changes

2023-11-11 11:44 UTC, ricardoV94 requested changes

2023-11-11 11:44 UTC, ricardoV94 commented on docs/source/api/shape_utils.rst
> +   broadcast_dist_samples_shape
We don't need this is the user-facing docs, it's a legacy method that we want to get rid of

2023-11-11 11:44 UTC, ricardoV94 commented on pymc/distributions/shape_utils.py
> +    new_size : Union[int, Tuple[int, ...]]
New size can be symbolic (i.e., Pytensor Variables)

2023-11-13 11:03 UTC, ricardoV94 approved these changes

2023-11-18 08:10 UTC, UditNayak commented
Hi @ricardoV94 , I tried to sovle this pre-commit Failure. But unable to fix this. Please guide me.

2023-11-18 11:23 UTC, twiecki commented
/pre-commit run

2023-11-28 18:15 UTC, UditNayak commented
Hi @twiecki the pre-commit issue is still unresolved. What else can i do on this PR.

2023-11-28 20:42 UTC, twiecki commented
@UditNayak You need to run pre-commit locally.

2026-06-06 11:07 UTC, closed without merging