Rectify Return type hint
pymc-devs/pymc pull request #7013
Opened 2023-11-14 19:03 UTC by vivek-anand-singh

Fixes #6811 

Rectify Return type hint for `find_measurable_comparisons`

2023-11-26 15:36 UTC, larryshamalama commented
Hi @vivek-anand-singh, thanks for your PR! Apologies for getting back to you late. Please don't hesitate to ping me (or any devs you want to review your PR) via the comment section next time :)

There are some other places where we would need to rectify type hints. Would you like to include those changes in this PR? I found the occurrences for your convenience

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/checks.py#L66

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/checks.py#L119

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/cumsum.py#L80

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/censoring.py#L65

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/censoring.py#L160

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/binary.py#L136

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/tensor.py#L200

2023-11-26 15:38 UTC, larryshamalama requested changes
Hi @vivek-anand-singh, thanks for your PR! Apologies for getting back to you late. Please don't hesitate to ping me (or any devs you want to review your PR) via the comment section next time :)

There are some other places where we would need to rectify type hints. Would you like to include those changes in this PR? I found the occurrences for your convenience

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/checks.py#L66

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/checks.py#L119

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/cumsum.py#L80

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/censoring.py#L65

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/censoring.py#L160

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/binary.py#L136

https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/tensor.py#L200-L202

When you would like for me to have a look again, you can request my revision around the top right of this PR

2023-11-29 18:49 UTC, vivek-anand-singh commented
https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/tensor.py#L200-L202


Hi @larryshamalama Thanks for the feedback ! should we change both `MeasurableMakeVector`and `MeasurableJoin` to `TensorVariable`?

2024-02-01 17:57 UTC, larryshamalama commented
Hi @vivek-anand-singh, so sorry for the delay, holidays, travels and studies came in the way of my OSS involvement... You can perhaps just do:

```python
def find_measurable_stacks( 
     fgraph, node 
 ) -> Optional[List[TensorVariable]]: 
```
FYI: this issue is being worked on in #7093. Because time has passed (which is my fault), I will add both of you as co-authors to whichever PR gets merged.

2024-02-01 19:39 UTC, vivek-anand-singh commented
Thanks for the response, Actually my exams are going on so I will do this after 2 days

2024-02-03 15:22 UTC, larryshamalama commented
#7093 is pretty much completed, so we are probably going to merge that PR and close this one. Again, apologies for the mix of delays; in principle, we should prioritize preceding PRs but there was a miscommunication here. We can add you as a co-author when merging the other PR.

2024-02-06 09:02 UTC, ricardoV94 commented
Added as a co-author in https://github.com/pymc-devs/pymc/pull/7125/commits/fb1c48fb9deced8efdedd5430483c3600b57625c

Sorry for the trouble!

2024-02-06 09:02 UTC, closed without merging