Removing comp_shape from class NormalMixture
pymc-devs/pymc pull request #7098
Opened 2024-01-11 17:49 UTC by mohammed052

This modification assumes that the Mixture class automatically handles the reshaping of component batch dimensions, and there is no longer a need to explicitly specify the comp_shape

## Description

## Related Issue

- [x] Closes #6986 

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [x] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

2024-01-15 08:40 UTC, ricardoV94 approved these changes

2024-01-15 08:40 UTC, ricardoV94 commented
Thanks @mohammed052, running that tests and we can merge if everything passes

2024-01-15 09:04 UTC, ricardoV94 commented
@mohammed052 you can see here some tests failed because they were still using the removed keyword: https://github.com/pymc-devs/pymc/actions/runs/7492576052/job/20484268751?pr=7098

We need to tweak the tests to not use it, but keep the same behavior otherwise.

2024-01-15 14:01 UTC, mohammed052 commented
@ricardoV94 can you please elaborate on what needs to be done next to tweak the tests

2024-01-15 15:40 UTC, ricardoV94 commented
@mohammed052 you'll need to investigate yourself, and for that it may be useful to run the tests locally to see what they are doing

2024-02-01 17:52 UTC, larryshamalama requested changes
Hi @mohammed052, as @ricardoV94 mentioned, you will have to adjust tests in `test_mixture.py` as `comp_shape` is still passed as an argument to `NormalMixture`, which is why the tests are failing. Notice the lines where we have `extra_args={"comp_shape": 2}`. See snippets below. Once all tests pass, this PR would be ready to merge :)

Let us know if you have any other questions!

https://github.com/pymc-devs/pymc/blob/94020c9e560fc3ae12f89f9e5547a05df7d5f1ee/tests/distributions/test_mixture.py#L858-L884

https://github.com/pymc-devs/pymc/blob/94020c9e560fc3ae12f89f9e5547a05df7d5f1ee/tests/distributions/test_mixture.py#L893-L907

2024-02-02 08:30 UTC, mohammed052 commented
I was facing difficulty earlier in identifying the problem in tests.Thank You @larryshamalama for your input.
I have made required changes in test_mixture.py. @ricardoV94  kindly review them.

2024-02-07 00:01 UTC, larryshamalama commented
> I was facing difficulty earlier in identifying the problem in tests.Thank You @larryshamalama for your input. I have made required changes in test_mixture.py. @ricardoV94 kindly review them.

There seems to be a lot more tests in `test_mixture.py` that has `comp_shape` as an argument, notably `test_normal_mixture_nd`. To be more time efficient, I can't identify every instance where these tests need modifications; there seem to be more. However, akin to my previous comment, the edits should be very similar

2024-02-12 12:46 UTC, mohammed052 commented
I made a few more changes last week, @ricardoV94 @larryshamalama can you review the pr once.

2024-03-22 11:44 UTC, ricardoV94 approved these changes

2024-03-25 04:26 UTC, twiecki commented
@mohammed052 you need to run pre-commit
```
diff --git a/tests/distributions/test_mixture.py b/tests/distributions/test_mixture.py
index ec1baa7..7ce6084 100644
--- a/tests/distributions/test_mixture.py
+++ b/tests/distributions/test_mixture.py
@@ -821,9 +821,7 @@ class TestNormalMixture:
             taus = Gamma("taus", alpha=1, beta=1, shape=comp_shape)
             ws = Dirichlet("ws", np.ones(ncomp), shape=(ncomp,))
             mixture0 = NormalMixture("m", w=ws, mu=mus, tau=taus, shape=nd)
-            obs0 = NormalMixture(
-                "obs", w=ws, mu=mus, tau=taus, observed=observed
-            )
+            obs0 = NormalMixture("obs", w=ws, mu=mus, tau=taus, observed=observed)
 
         with Model() as model1:
```

2024-03-25 09:00 UTC, ricardoV94 commented
I was the one rebasing this PR

2024-03-25 09:16 UTC, twiecki approved these changes

2024-03-25 09:37 UTC, merged