Fix failing vi test
pymc-devs/pymc pull request #7144
Opened 2024-02-07 08:47 UTC by aerubanov

## Description
In pytest 7 missing warning were ignored if some exception was raised, but pytest 8 checking them and that`s why `test_fit_start[SVGD-mini]` fails. I replaced `pytest.warn()` by manual check for warning raised. 

## Related Issue

- [ ] Closes #
- [x] Related to #7136

## Type of change

- [ ] New feature / enhancement
- [x] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

2024-02-07 09:27 UTC, ferrine commented
Many thanks investigating that!

2024-02-07 10:37 UTC, ricardoV94 requested changes

2024-02-07 10:37 UTC, ricardoV94 commented on tests/variational/test_inference.py
> -    if observed_value.name.startswith("minibatch"):
What about something like

```python
expected_warning: bool = ...

with warnings.catch_warns(record=True) as record:
  ...
  try:
    ...
  except NotImplementedInference as err:
    ...
    
if expected_warning:
  assert len(record) == 1
  assert ... # Check expected warning
else:
  assert not record
```

We still want to raise for unexpected warnings

2024-02-07 11:31 UTC, aerubanov commented on tests/variational/test_inference.py
> -    if observed_value.name.startswith("minibatch"):
@ricardoV94 I added check for unexpected warnings

2024-02-08 07:44 UTC, ricardoV94 commented on tests/variational/test_inference.py
> +        assert len(record) > 1
Why is it bigger than 1?

2024-02-08 08:15 UTC, aerubanov commented on tests/variational/test_inference.py
> +        assert len(record) > 1
Ups, just my stupid mistake

2024-02-08 09:28 UTC, ricardoV94 approved these changes

2024-02-08 09:28 UTC, merged

2024-02-08 09:29 UTC, ricardoV94 commented
Thanks a ton @aerubanov!