Add introduction section to Transformations API page to document role of Transforms
pymc-devs/pymc pull request #7232
Opened 2024-03-29 23:18 UTC by mkusnetsov

## Description

This PR adds an introduction section to the Transformations API page to:
- explain the principal purpose of transforms
- warn that most users don't need to play with these and that most attempts to do so don't do what users tend to think
- provide some guidance on when tweaking transforms may be appropriate and what other options user have when wanting to deal with transformed random variables

In addition this PR:
- removes a seemingly incorrect deprecation comment next to the `ordered` transform (I think it was accidentally left over from when `univariate_ordered` was deprecated)
- removes mention of `SumsTo1`, which is being deprecated
- organises instance and class names in the autosummary to 
  1. alphebtize them, and
  2. add missing class names for the included instances

This PR assumes that the issue #5674 is closed (via PR #7207) to avoid extensive (and somewhat non-intuitive to casual user) guidance that will shortly be outdated

## Related Issue

- [x] Closes #7040
- [x] Related to #6975, #5674, #7009

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [x] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

2024-04-02 09:20 UTC, ricardoV94 approved these changes
This explanation is absolutely incredible!

2024-04-02 09:22 UTC, ricardoV94 requested changes
Just a small suggestion, we have both `transform` and `default_transform` now. All you said about `default_transform` is correct. When users want to add other constraints but not modify the default one, they should use the `transform` kwarg. Under the hood, we will build a ChainTransform, that applies the user provided transform on top of the default one.

2024-04-02 22:56 UTC, mkusnetsov commented
Thanks, @ricardoV94! That's a good point - I pushed some changes to clarify `transform` kwarg as distinct from `default_transform`.

But I might be doing something wrong? Although I can see the commits and the changes, the preview documentation is still showing the original version, not the revised one... (I know it takes a while to re-build but it seems to be saying "Read the Docs build succeeded!")

2024-04-03 07:26 UTC, ricardoV94 commented
> But I might be doing something wrong? Although I can see the commits and the changes, the preview documentation is still showing the original version, not the revised one... (I know it takes a while to re-build but it seems to be saying "Read the Docs build succeeded!")

It takes some time for the preview to update. I think it's correct now? https://pymcio--7232.org.readthedocs.build/projects/docs/en/7232/api/distributions/transforms.html

2024-04-03 07:28 UTC, ricardoV94 approved these changes
I think this is perfect as is. I would just wait for the related PR to be merged, so that our docs are not "ahead of time"

2024-04-03 19:03 UTC, mkusnetsov commented
Thank you for the kind words! It is correct now, yes. Will know that it takes a while, in the future. And yes - it absolutely makes sense to wait for the other PR.

I left some [open questions](https://github.com/pymc-devs/pymc/issues/7040#issuecomment-2027815599) on the underlying issue. Are any of them worth pursuing either in a separate issue or a discussion? Just checking because I assume once that issue is closed they might get lost.

2024-04-12 15:57 UTC, OriolAbril approved these changes
I review docs related PRs quite sparsely if I have time and after seeing this one I wanted to add my praise too at use of rST, both at syntax level and conceptual level 😄 📚 

Also, in case someone wonders, the fact that references to pymc.sample, pymc.sample_prior_predictive... are not (yet) rendered as links in the rtd preview is an issue with how those are documented, once that is fixed all cross-references here will work

2024-04-19 07:24 UTC, merged

2024-04-19 07:25 UTC, ricardoV94 commented
Thanks a ton @mkusnetsov, don't hesitate in opening issues/PRs for other areas you find documentation to be lacking