Add time remaining column to progress bars
pymc-devs/pymc pull request #7273
Opened 2024-04-21 22:09 UTC by fonnesbeck

## Description

Adds `TimeRemainingColumn` to progress bar where appropriate

## Related Issue

- [x ] Closes #7269 
- [ ] Related to #

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [x] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

2024-04-22 08:20 UTC, ricardoV94 commented
While we're here can we also try to fix #7264 ?

This issue suggests there should be `transient` flag we can play with? https://github.com/Textualize/rich/issues/110

2024-04-23 13:46 UTC, fonnesbeck commented
Closes #7264

2024-04-24 07:13 UTC, ricardoV94 commented on pymc/sampling/forward.py
> +        ) as progress:
We should do this everywhere we use the Progressbar no? `sample`, `smc` and here: https://github.com/pymc-devs/pymc/blob/6761c0c73ba07cc9dc51ec3adab7f1aa5f76b23d/pymc/backends/arviz.py#L662

Not sure if I am missing any other place

2024-04-24 14:28 UTC, fonnesbeck commented on pymc/sampling/forward.py
> +        ) as progress:
Its not implemented the exact same way everywhere (some progress bars are simpler) but I will add this where it might be applicable.

2024-04-24 14:31 UTC, fonnesbeck commented
Will try and fix #7278 here as well.

2024-04-25 16:44 UTC, fonnesbeck commented
![image](https://github.com/pymc-devs/pymc/assets/81476/71be4bc2-badb-404c-a243-3db3b6fce454)

2024-04-25 16:52 UTC, ricardoV94 commented
Branch seems to have some conflicts?

2024-04-25 20:00 UTC, zaxtax requested changes
Looks good. After my comment is addressed should be good to merge.

2024-04-25 20:00 UTC, zaxtax commented on pymc/backends/arviz.py
> +        task = progress.add_task("Computinng ...", total=n_pts, visible=progressbar)
Typo that snuck back in?

2024-04-26 13:40 UTC, zaxtax approved these changes
LGTM

2024-04-26 17:24 UTC, merged